<a href="https://colab.research.google.com/github/antonpetkoff/identifier-suggestion/blob/master/notebooks/00-colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# import utilities
import os
import shutil
from subprocess import check_output

In [2]:
!nvidia-smi

Fri Jun  5 09:38:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [4]:
%env WORKSPACE_DIR=/content/gdrive/My Drive/src

# TODO: how can one read an environment variable?!?
%cd '/content/gdrive/My Drive/src'

env: WORKSPACE_DIR=/content/gdrive/My Drive/src
/content/gdrive/My Drive/src


In [0]:
timestamp = check_output(['date', '-u', "+%Y-%m-%dT%H-%M-%S"]).decode('utf-8').strip()

os.environ['PROJECT_DIR'] = os.path.join(
    os.environ['WORKSPACE_DIR'],
    f'identifier-suggestion-{timestamp}',
)

In [6]:
!git clone https://github.com/antonpetkoff/identifier-suggestion.git --depth 1 "${PROJECT_DIR}"

Cloning into '/content/gdrive/My Drive/src/identifier-suggestion-2020-06-05T09-38-13'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 83 (delta 0), reused 46 (delta 0), pack-reused 0
Unpacking objects: 100% (83/83), done.


In [0]:
os.chdir(os.environ['PROJECT_DIR'])

In [8]:
!pwd
!ls -l

/content/gdrive/My Drive/src/identifier-suggestion-2020-06-05T09-38-13
total 60
-rw-------  1 root root 35149 Jun  5 09:38 LICENSE
drwx------  2 root root  4096 Jun  5 09:38 notebooks
-rw-------  1 root root  9130 Jun  5 09:38 README.md
drwx------  2 root root  4096 Jun  5 09:38 requirements
drwx------ 12 root root  4096 Jun  5 09:38 src
drwx------  3 root root  4096 Jun  5 09:38 vscode-extension


In [9]:
%tensorflow_version 2.x

import tensorflow
print(tensorflow.__version__)

2.2.0


In [10]:
# Google Colab has standard libraries like numpy, pandas, matplotlib and TF (of course) pre-installed
!pip install -r requirements/colab.txt

In [11]:
# provide secrets to the project, e.g. access to wandb
shutil.copy(
    os.path.join(os.environ['WORKSPACE_DIR'], 'secrets/.env'),
    os.environ['PROJECT_DIR']
)

'/content/gdrive/My Drive/src/identifier-suggestion-2020-06-05T09-38-13/.env'

In [0]:
# monkey-patch (mock) os.symlink to be a noop, because wandb.save() uses it, but it is not supported by Google Colab Notebooks
os.symlink = lambda *x: print('Executing mocked noop symlink with arguments', x)

In [13]:
from argparse import Namespace
from src.pipelines.baseline import run

params = {
  'file_data_raw': '../data/interim/method-names-rich/elasticsearch.csv',
  'file_checkpoint_dir': 'models/checkpoints/baseline/',
  'dir_preprocessed_data': '../data/interim/preprocessed/',
  'max_input_length': 200,
  'max_output_length': 8,
  'input_vocab_size': 20000,
  'input_embedding_dim': 64,
  'output_vocab_size': 6000,
  'output_embedding_dim': 64,
  'latent_dim': 256,
  'learning_rate': 0.0001,
  'epochs': 25,
  'batch_size': 512,
  'random_seed': 1,
  'eval_averaging': 'macro'
}

run(Namespace(**params))

Initializing logger


wandb: Wandb version 0.8.36 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


Experiment parameters:  Namespace(batch_size=512, dir_preprocessed_data='../data/interim/preprocessed/', epochs=25, eval_averaging='macro', file_checkpoint_dir='models/checkpoints/baseline/', file_data_raw='../data/interim/method-names-rich/elasticsearch.csv', input_embedding_dim=64, input_vocab_size=20000, latent_dim=256, learning_rate=0.0001, max_input_length=200, max_output_length=8, output_embedding_dim=64, output_vocab_size=6000, random_seed=1)
Loading preprocessed files...
Loaded input vocabulary.
Loaded output vocabulary.
Loaded preprocessed files.
Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
EncoderEmbedding (Embedding) multiple                  1280000   
_________________________________________________________________
EncoderLSTM (LSTM)           multiple                  328704    
Total params: 1,608,704
Trainable params: 1,608,704
Non-trainable params: 0
_______________

wandb: Visualizing heatmap.


epoch 1 evaluation time: 5.438562393188477 sec
epoch evaluation:  {'epoch': 1, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=3.0431302>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.13613209>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=2.2688682e-05>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.00016666666>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=3.994022e-05>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 2 - batch 10 - loss 3.1390929222106934 - precision 2.269810102006886e-05 - recall 0.00016666666488163173 - f1 3.995481529273093e-05 - sparse_categorical_accuracy 0.13618861138820648
epoch 2 - batch 20 - loss 3.074592351913452 - precision 2.266555020469241e-05 - recall 0.00016666666488163173 - f1 3.99043747165706e-05 - sparse_categorical_accuracy 0.13599330186843872
epoch 2 - batch 30 - loss 3.1205291748046875 - precision 2.26795000344282e-05 - recall 0.00016666666488163173 - f1 3.992599158664234e-05 - sparse_categorical_accuracy 0.13607700169086456
epoch 2 - batch 40 - loss 2.9892373085021973 - precision 2.2685313524561934e-05 - recall 0.00016666666488163173 - f1 3.99349992221687e-05 - sparse_categorical_accuracy 0.13611188530921936
epoch 2 - batch 50 - loss 3.0404858589172363 - precision 2.2667411030852236e-05 - recall 0.00016666666488163173 - f1 3.990725599578582e-05 - sparse_categorical_accuracy 0.1360044628381729
epoch 2 - batch 60 - loss 3.173475980758667 - precision 2.26469

wandb: Visualizing heatmap.


epoch 2 evaluation time: 5.475856065750122 sec
epoch evaluation:  {'epoch': 2, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.8364644>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.1675538>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=6.2175124e-05>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.00033333333>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.00010451345>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 - batch 10 - loss 2.7724556922912598 - precision 6.166897946968675e-05 - recall 0.00033333332976326346 - f1 0.00010383214248577133 - sparse_categorical_accuracy 0.16738280653953552
epoch 3 - batch 20 - loss 2.714120388031006 - precision 6.21028448222205e-05 - recall 0.00033333332976326346 - f1 0.00010441749327583238 - sparse_categorical_accuracy 0.16757813096046448
epoch 3 - batch 30 - loss 2.7979602813720703 - precision 6.224850949365646e-05 - recall 0.00033333332976326346 - f1 0.0001046123870764859 - sparse_categorical_accuracy 0.1675967276096344
epoch 3 - batch 40 - loss 2.770953416824341 - precision 6.258196663111448e-05 - recall 0.00033333332976326346 - f1 0.00010506447142688558 - sparse_categorical_accuracy 0.1678989976644516
epoch 3 - batch 50 - loss 2.828463315963745 - precision 6.245843542274088e-05 - recall 0.00033333332976326346 - f1 0.00010489664418855682 - sparse_categorical_accuracy 0.16776227951049805
epoch 3 - batch 60 - loss 2.75195050239563 - precision 6.26099

wandb: Visualizing heatmap.


epoch 3 evaluation time: 5.4835100173950195 sec
epoch evaluation:  {'epoch': 3, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.6270823>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.17206101>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.00016895219>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0005>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.00023541244>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 saved checkpoint: models/checkpoints/baseline/ckpt-2
epoch 4 - batch 10 - loss 2.7563345432281494 - precision 0.00017316130106337368 - recall 0.0005000000237487257 - f1 0.0002387122658547014 - sparse_categorical_accuracy 0.17240513861179352
epoch 4 - batch 20 - loss 2.583984136581421 - precision 0.00017184052558150142 - recall 0.0005000000237487257 - f1 0.00023725100618321449 - sparse_categorical_accuracy 0.17195869982242584
epoch 4 - batch 30 - loss 2.6349539756774902 - precision 0.00017745193326845765 - recall 0.0005052410997450352 - f1 0.00024338551156688482 - sparse_categorical_accuracy 0.17250743508338928
epoch 4 - batch 40 - loss 2.6575706005096436 - precision 0.00017915056378114969 - recall 0.0005259434110485017 - f1 0.0002480962430126965 - sparse_categorical_accuracy 0.17294922471046448
epoch 4 - batch 50 - loss 2.657611846923828 - precision 0.0001809586538001895 - recall 0.0005527989706024528 - f1 0.00025109347188845277 - sparse_categorical_accuracy 0.17292968928813934

wandb: Visualizing heatmap.


epoch 4 evaluation time: 5.566169023513794 sec
epoch evaluation:  {'epoch': 4, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.560841>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.17846411>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.00058165414>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0010064937>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.00050468725>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 5 - batch 10 - loss 2.595071315765381 - precision 0.0007086393306963146 - recall 0.0009985951473936439 - f1 0.000500920694321394 - sparse_categorical_accuracy 0.17812499403953552
epoch 5 - batch 20 - loss 2.5348713397979736 - precision 0.0006343306740745902 - recall 0.0010377316502854228 - f1 0.0005520742852240801 - sparse_categorical_accuracy 0.17876674234867096
epoch 5 - batch 30 - loss 2.5927186012268066 - precision 0.0007210426265373826 - recall 0.0010987590067088604 - f1 0.0006253647152334452 - sparse_categorical_accuracy 0.17932477593421936
epoch 5 - batch 40 - loss 2.534806966781616 - precision 0.0008796043111942708 - recall 0.001139034633524716 - f1 0.0006686029955744743 - sparse_categorical_accuracy 0.17971539497375488
epoch 5 - batch 50 - loss 2.538651704788208 - precision 0.0008726596715860069 - recall 0.0011621547164395452 - f1 0.0006823143921792507 - sparse_categorical_accuracy 0.17985491454601288
epoch 5 - batch 60 - loss 2.4806861877441406 - precision 0.00086647452

wandb: Visualizing heatmap.


epoch 5 evaluation time: 5.571761846542358 sec
epoch evaluation:  {'epoch': 5, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.4713697>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.19298735>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0014886449>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0017136437>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0011291516>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 - batch 10 - loss 2.4280338287353516 - precision 0.001479107653722167 - recall 0.0016236035153269768 - f1 0.0010076023172587156 - sparse_categorical_accuracy 0.19330357015132904
epoch 6 - batch 20 - loss 2.4189248085021973 - precision 0.001422386965714395 - recall 0.001689566415734589 - f1 0.0010896355379372835 - sparse_categorical_accuracy 0.19394531846046448
epoch 6 - batch 30 - loss 2.3105030059814453 - precision 0.0014168077614158392 - recall 0.001770828035660088 - f1 0.0011497270315885544 - sparse_categorical_accuracy 0.19473586976528168
epoch 6 - batch 40 - loss 2.3631765842437744 - precision 0.0015503717586398125 - recall 0.0018591097323223948 - f1 0.0011914519127458334 - sparse_categorical_accuracy 0.19571010768413544
epoch 6 - batch 50 - loss 2.380980968475342 - precision 0.001443163608200848 - recall 0.0019391628447920084 - f1 0.0012533921981230378 - sparse_categorical_accuracy 0.19619977474212646
epoch 6 - batch 60 - loss 2.4411380290985107 - precision 0.001445051166

wandb: Visualizing heatmap.


epoch 6 evaluation time: 5.568853139877319 sec
epoch evaluation:  {'epoch': 6, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.3900292>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.20283882>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0019926815>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.002989063>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.001959412>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 saved checkpoint: models/checkpoints/baseline/ckpt-3
epoch 7 - batch 10 - loss 2.316927671432495 - precision 0.0017840178916230798 - recall 0.0029458431527018547 - f1 0.0018651677528396249 - sparse_categorical_accuracy 0.20231585204601288
epoch 7 - batch 20 - loss 2.2846505641937256 - precision 0.0019126394763588905 - recall 0.0030635728035122156 - f1 0.0019749414641410112 - sparse_categorical_accuracy 0.2033342570066452
epoch 7 - batch 30 - loss 2.337015390396118 - precision 0.0018505345797166228 - recall 0.0031163019593805075 - f1 0.0019804746843874454 - sparse_categorical_accuracy 0.20466889441013336
epoch 7 - batch 40 - loss 2.3310964107513428 - precision 0.00184913189150393 - recall 0.003158178413286805 - f1 0.001994210295379162 - sparse_categorical_accuracy 0.20564313232898712
epoch 7 - batch 50 - loss 2.3420345783233643 - precision 0.0018494828836992383 - recall 0.003156183520331979 - f1 0.001994016580283642 - sparse_categorical_accuracy 0.2053738832473755
epoch 7 - batc

wandb: Visualizing heatmap.


epoch 7 evaluation time: 5.577656269073486 sec
epoch evaluation:  {'epoch': 7, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.3222258>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.20878406>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.00223768>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.003432956>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0021968347>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 8 - batch 10 - loss 2.293452739715576 - precision 0.002237858949229121 - recall 0.003421113593503833 - f1 0.002138426760211587 - sparse_categorical_accuracy 0.2057756632566452
epoch 8 - batch 20 - loss 2.2586252689361572 - precision 0.002372227143496275 - recall 0.003504066728055477 - f1 0.0022161900997161865 - sparse_categorical_accuracy 0.2090541273355484
epoch 8 - batch 30 - loss 2.2348973751068115 - precision 0.0022974307648837566 - recall 0.003535936353728175 - f1 0.002252850914373994 - sparse_categorical_accuracy 0.20961681008338928
epoch 8 - batch 40 - loss 2.2676022052764893 - precision 0.002354905242100358 - recall 0.0035754323471337557 - f1 0.002283056266605854 - sparse_categorical_accuracy 0.20988421142101288
epoch 8 - batch 50 - loss 2.2161953449249268 - precision 0.002727295970544219 - recall 0.0036101939622312784 - f1 0.002314598998054862 - sparse_categorical_accuracy 0.2098270058631897
epoch 8 - batch 60 - loss 2.2814629077911377 - precision 0.0028985675889998674 -

wandb: Visualizing heatmap.


epoch 8 evaluation time: 5.702206134796143 sec
epoch evaluation:  {'epoch': 8, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.2819586>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.21181747>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0027488226>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0040510497>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.002675587>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 - batch 10 - loss 2.3498878479003906 - precision 0.0027544412296265364 - recall 0.0041115921922028065 - f1 0.0026900453958660364 - sparse_categorical_accuracy 0.21012835204601288
epoch 9 - batch 20 - loss 2.3945538997650146 - precision 0.002859413158148527 - recall 0.004175372887402773 - f1 0.0027959600556641817 - sparse_categorical_accuracy 0.21075613796710968
epoch 9 - batch 30 - loss 2.1856276988983154 - precision 0.0033749272115528584 - recall 0.004294733516871929 - f1 0.002904168562963605 - sparse_categorical_accuracy 0.21175594627857208
epoch 9 - batch 40 - loss 2.3581395149230957 - precision 0.0036804189439862967 - recall 0.004331493284553289 - f1 0.0029538460075855255 - sparse_categorical_accuracy 0.21213030815124512
epoch 9 - batch 50 - loss 2.128979206085205 - precision 0.003891920205205679 - recall 0.004372479859739542 - f1 0.0030433868523687124 - sparse_categorical_accuracy 0.2117578089237213
epoch 9 - batch 60 - loss 2.1254591941833496 - precision 0.003931424114853

wandb: Visualizing heatmap.


epoch 9 evaluation time: 5.621574878692627 sec
epoch evaluation:  {'epoch': 9, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.2555006>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.212769>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.003741188>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0048627453>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0033585993>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 saved checkpoint: models/checkpoints/baseline/ckpt-4
epoch 10 - batch 10 - loss 2.1603944301605225 - precision 0.0036077341064810753 - recall 0.005090320948511362 - f1 0.0034875026904046535 - sparse_categorical_accuracy 0.2144252210855484
epoch 10 - batch 20 - loss 2.1228044033050537 - precision 0.004348136484622955 - recall 0.005193044897168875 - f1 0.0035206566099077463 - sparse_categorical_accuracy 0.21446707844734192
epoch 10 - batch 30 - loss 2.1640846729278564 - precision 0.004608626943081617 - recall 0.005251411348581314 - f1 0.0036129497457295656 - sparse_categorical_accuracy 0.21455542743206024
epoch 10 - batch 40 - loss 2.115621566772461 - precision 0.004748726263642311 - recall 0.005280764307826757 - f1 0.003669676138088107 - sparse_categorical_accuracy 0.21462750434875488
epoch 10 - batch 50 - loss 2.273580312728882 - precision 0.005184985231608152 - recall 0.005310369655489922 - f1 0.00373278115876019 - sparse_categorical_accuracy 0.21363839507102966
epoch 10 - bat

wandb: Visualizing heatmap.


epoch 10 evaluation time: 5.575531005859375 sec
epoch evaluation:  {'epoch': 10, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.2346075>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.21424994>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.005433916>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0059809596>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.004084104>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 11 - batch 10 - loss 2.0913751125335693 - precision 0.005694152787327766 - recall 0.00629292381927371 - f1 0.00447411835193634 - sparse_categorical_accuracy 0.21445313096046448
epoch 11 - batch 20 - loss 2.154146671295166 - precision 0.005817458964884281 - recall 0.006351257208734751 - f1 0.004523338284343481 - sparse_categorical_accuracy 0.21558314561843872
epoch 11 - batch 30 - loss 2.1536850929260254 - precision 0.005744662135839462 - recall 0.00621238024905324 - f1 0.004413506016135216 - sparse_categorical_accuracy 0.215913325548172
epoch 11 - batch 40 - loss 2.1591529846191406 - precision 0.0059163691475987434 - recall 0.006222900934517384 - f1 0.0044264583848416805 - sparse_categorical_accuracy 0.21568778157234192
epoch 11 - batch 50 - loss 2.110098123550415 - precision 0.006500843912363052 - recall 0.0062949019484221935 - f1 0.004570735618472099 - sparse_categorical_accuracy 0.21587052941322327
epoch 11 - batch 60 - loss 2.2569873332977295 - precision 0.006733491085469723 

wandb: Visualizing heatmap.


epoch 11 evaluation time: 5.597870826721191 sec
epoch evaluation:  {'epoch': 11, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.2155368>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2177484>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.00733288>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0072987657>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0053644106>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 - batch 10 - loss 2.1840059757232666 - precision 0.006088754162192345 - recall 0.007415035739541054 - f1 0.005367830861359835 - sparse_categorical_accuracy 0.21551339328289032
epoch 12 - batch 20 - loss 2.066771984100342 - precision 0.006328276824206114 - recall 0.007446019444614649 - f1 0.005375337786972523 - sparse_categorical_accuracy 0.21788504719734192
epoch 12 - batch 30 - loss 2.0849668979644775 - precision 0.006909241434186697 - recall 0.007452493533492088 - f1 0.0054260240867733955 - sparse_categorical_accuracy 0.21822915971279144
epoch 12 - batch 40 - loss 2.099208354949951 - precision 0.007772508077323437 - recall 0.007491299416869879 - f1 0.005547224543988705 - sparse_categorical_accuracy 0.21947544813156128
epoch 12 - batch 50 - loss 2.2180569171905518 - precision 0.00820219237357378 - recall 0.00757494056597352 - f1 0.005671320483088493 - sparse_categorical_accuracy 0.21883369982242584
epoch 12 - batch 60 - loss 2.1584935188293457 - precision 0.008228751830756664

wandb: Visualizing heatmap.


epoch 12 evaluation time: 5.580463886260986 sec
epoch evaluation:  {'epoch': 12, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.201161>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.21780564>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.00730293>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.008421577>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.006224458>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 saved checkpoint: models/checkpoints/baseline/ckpt-5
epoch 13 - batch 10 - loss 2.1188347339630127 - precision 0.0074857184663414955 - recall 0.008631843142211437 - f1 0.006304802373051643 - sparse_categorical_accuracy 0.21785713732242584
epoch 13 - batch 20 - loss 2.033879041671753 - precision 0.008209106512367725 - recall 0.008615986444056034 - f1 0.006429826840758324 - sparse_categorical_accuracy 0.2196568101644516
epoch 13 - batch 30 - loss 2.02309513092041 - precision 0.0086569394916296 - recall 0.008522194810211658 - f1 0.006525913253426552 - sparse_categorical_accuracy 0.21952195465564728
epoch 13 - batch 40 - loss 2.156240224838257 - precision 0.009234322234988213 - recall 0.00856763031333685 - f1 0.006614528596401215 - sparse_categorical_accuracy 0.22051478922367096
epoch 13 - batch 50 - loss 2.031017303466797 - precision 0.009494924917817116 - recall 0.008707263506948948 - f1 0.006775094196200371 - sparse_categorical_accuracy 0.22092634439468384
epoch 13 - batch 60 -

wandb: Visualizing heatmap.


epoch 13 evaluation time: 5.5852508544921875 sec
epoch evaluation:  {'epoch': 13, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.181966>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22190505>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.008957948>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.01000339>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.007466643>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 14 - batch 10 - loss 2.064260959625244 - precision 0.007434165105223656 - recall 0.0096385907381773 - f1 0.007091843988746405 - sparse_categorical_accuracy 0.22022879123687744
epoch 14 - batch 20 - loss 2.040743350982666 - precision 0.00808454304933548 - recall 0.009588602930307388 - f1 0.007199663203209639 - sparse_categorical_accuracy 0.22269810736179352
epoch 14 - batch 30 - loss 2.0668609142303467 - precision 0.008773750625550747 - recall 0.009552981704473495 - f1 0.007262883707880974 - sparse_categorical_accuracy 0.22392113506793976
epoch 14 - batch 40 - loss 2.125560998916626 - precision 0.00938955694437027 - recall 0.009664583019912243 - f1 0.007460399530827999 - sparse_categorical_accuracy 0.22393973171710968
epoch 14 - batch 50 - loss 2.0797173976898193 - precision 0.009778328239917755 - recall 0.009795503690838814 - f1 0.00753897987306118 - sparse_categorical_accuracy 0.22386719286441803
epoch 14 - batch 60 - loss 2.118830442428589 - precision 0.010229342617094517 - rec

wandb: Visualizing heatmap.


epoch 14 evaluation time: 5.569990396499634 sec
epoch evaluation:  {'epoch': 14, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1698399>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2235863>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.009569223>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.010760815>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.008096026>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 - batch 10 - loss 2.1055920124053955 - precision 0.008957413025200367 - recall 0.010832181200385094 - f1 0.00789930671453476 - sparse_categorical_accuracy 0.22508370876312256
epoch 15 - batch 20 - loss 2.037630319595337 - precision 0.009633670561015606 - recall 0.010836029425263405 - f1 0.00790335237979889 - sparse_categorical_accuracy 0.22622768580913544
epoch 15 - batch 30 - loss 2.2286550998687744 - precision 0.01045980490744114 - recall 0.01096612960100174 - f1 0.008153128437697887 - sparse_categorical_accuracy 0.2261904776096344
epoch 15 - batch 40 - loss 2.106046438217163 - precision 0.0113509651273489 - recall 0.0110851489007473 - f1 0.008325163275003433 - sparse_categorical_accuracy 0.22657644748687744
epoch 15 - batch 50 - loss 2.0339810848236084 - precision 0.011296026408672333 - recall 0.011230189353227615 - f1 0.008482356555759907 - sparse_categorical_accuracy 0.22618304193019867
epoch 15 - batch 60 - loss 2.02582049369812 - precision 0.011624690145254135 - recall 

wandb: Visualizing heatmap.


epoch 15 evaluation time: 5.594502210617065 sec
epoch evaluation:  {'epoch': 15, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1534724>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22561814>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.011512876>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.01171692>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.008902047>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 saved checkpoint: models/checkpoints/baseline/ckpt-6
epoch 16 - batch 10 - loss 2.068047523498535 - precision 0.010381958447396755 - recall 0.012206639163196087 - f1 0.009032133966684341 - sparse_categorical_accuracy 0.22633928060531616
epoch 16 - batch 20 - loss 1.9740097522735596 - precision 0.012208735570311546 - recall 0.011993815191090107 - f1 0.009192187339067459 - sparse_categorical_accuracy 0.22765067219734192
epoch 16 - batch 30 - loss 2.1221964359283447 - precision 0.013260622508823872 - recall 0.012169948779046535 - f1 0.009523996151983738 - sparse_categorical_accuracy 0.22818081080913544
epoch 16 - batch 40 - loss 2.1140973567962646 - precision 0.013190221041440964 - recall 0.012150907889008522 - f1 0.009564755484461784 - sparse_categorical_accuracy 0.22854351997375488
epoch 16 - batch 50 - loss 2.0805418491363525 - precision 0.013580510392785072 - recall 0.012307838536798954 - f1 0.009717262350022793 - sparse_categorical_accuracy 0.22860491275787354
epoch 16 - bat

wandb: Visualizing heatmap.


epoch 16 evaluation time: 5.563518285751343 sec
epoch evaluation:  {'epoch': 16, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1403387>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22543928>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.013475589>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0131475255>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.010102828>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 17 - batch 10 - loss 2.090106964111328 - precision 0.012200326658785343 - recall 0.013008945621550083 - f1 0.009786529466509819 - sparse_categorical_accuracy 0.22525112330913544
epoch 17 - batch 20 - loss 2.030017375946045 - precision 0.013257601298391819 - recall 0.013333873823285103 - f1 0.010309114120900631 - sparse_categorical_accuracy 0.22752511501312256
epoch 17 - batch 30 - loss 2.1386783123016357 - precision 0.014334120787680149 - recall 0.013233321718871593 - f1 0.010283341631293297 - sparse_categorical_accuracy 0.22854351997375488
epoch 17 - batch 40 - loss 2.0881500244140625 - precision 0.014740310609340668 - recall 0.013169420883059502 - f1 0.010356849990785122 - sparse_categorical_accuracy 0.2282366007566452
epoch 17 - batch 50 - loss 2.0035386085510254 - precision 0.015282461419701576 - recall 0.013322933577001095 - f1 0.010524031706154346 - sparse_categorical_accuracy 0.2282589226961136
epoch 17 - batch 60 - loss 1.9621152877807617 - precision 0.015386664308607578 

wandb: Visualizing heatmap.


epoch 17 evaluation time: 5.595157146453857 sec
epoch evaluation:  {'epoch': 17, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.131829>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22533911>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.014692917>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.014266644>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.011204026>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 - batch 10 - loss 1.9676843881607056 - precision 0.014527251943945885 - recall 0.014481944963335991 - f1 0.011325182393193245 - sparse_categorical_accuracy 0.23021763563156128
epoch 18 - batch 20 - loss 1.9517818689346313 - precision 0.01569681614637375 - recall 0.014590882696211338 - f1 0.011464831419289112 - sparse_categorical_accuracy 0.23205915093421936
epoch 18 - batch 30 - loss 1.9360870122909546 - precision 0.015869589522480965 - recall 0.01455481257289648 - f1 0.0115425456315279 - sparse_categorical_accuracy 0.23254278302192688
epoch 18 - batch 40 - loss 1.9592033624649048 - precision 0.016558565199375153 - recall 0.014580046758055687 - f1 0.0117556257173419 - sparse_categorical_accuracy 0.233154296875
epoch 18 - batch 50 - loss 2.0504491329193115 - precision 0.01675507053732872 - recall 0.01469243224710226 - f1 0.011791069060564041 - sparse_categorical_accuracy 0.23253905773162842
epoch 18 - batch 60 - loss 1.9857981204986572 - precision 0.01705632172524929 - recall 0

wandb: Visualizing heatmap.


epoch 18 evaluation time: 5.580002546310425 sec
epoch evaluation:  {'epoch': 18, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.1124508>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22873741>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.016143769>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.015535866>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.012182423>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 saved checkpoint: models/checkpoints/baseline/ckpt-7
epoch 19 - batch 10 - loss 2.07327938079834 - precision 0.015363438054919243 - recall 0.01570981554687023 - f1 0.01233486458659172 - sparse_categorical_accuracy 0.22965960204601288
epoch 19 - batch 20 - loss 1.9578068256378174 - precision 0.016606468707323074 - recall 0.016024215146899223 - f1 0.012768230400979519 - sparse_categorical_accuracy 0.23337054252624512
epoch 19 - batch 30 - loss 1.9943000078201294 - precision 0.017578212544322014 - recall 0.016009805724024773 - f1 0.01292955782264471 - sparse_categorical_accuracy 0.23462611436843872
epoch 19 - batch 40 - loss 2.0881192684173584 - precision 0.018013466149568558 - recall 0.016099635511636734 - f1 0.01307907234877348 - sparse_categorical_accuracy 0.23517020046710968
epoch 19 - batch 50 - loss 2.0224997997283936 - precision 0.018598493188619614 - recall 0.016120273619890213 - f1 0.013148789294064045 - sparse_categorical_accuracy 0.23420201241970062
epoch 19 - batch 60

wandb: Visualizing heatmap.


epoch 19 evaluation time: 5.563204765319824 sec
epoch evaluation:  {'epoch': 19, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.112494>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2279862>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.017899951>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.01683007>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.013591446>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 20 - batch 10 - loss 2.0002119541168213 - precision 0.017359498888254166 - recall 0.01741301268339157 - f1 0.01356242410838604 - sparse_categorical_accuracy 0.23406808078289032
epoch 20 - batch 20 - loss 1.999908208847046 - precision 0.018711606040596962 - recall 0.017288904637098312 - f1 0.013805490918457508 - sparse_categorical_accuracy 0.23515625298023224
epoch 20 - batch 30 - loss 1.9754995107650757 - precision 0.019749699160456657 - recall 0.01740962639451027 - f1 0.014245180413126945 - sparse_categorical_accuracy 0.23566778004169464
epoch 20 - batch 40 - loss 1.956849217414856 - precision 0.020443284884095192 - recall 0.017327403649687767 - f1 0.014371892437338829 - sparse_categorical_accuracy 0.23597237467765808
epoch 20 - batch 50 - loss 2.009612560272217 - precision 0.02130884863436222 - recall 0.017436204478144646 - f1 0.014507506974041462 - sparse_categorical_accuracy 0.23626115918159485
epoch 20 - batch 60 - loss 1.9927905797958374 - precision 0.021761247888207436 - r

wandb: Visualizing heatmap.


epoch 20 evaluation time: 5.58293604850769 sec
epoch evaluation:  {'epoch': 20, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.089577>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2316206>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.019367278>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.018430455>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.014757967>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 - batch 10 - loss 1.9140716791152954 - precision 0.016435842961072922 - recall 0.017831679433584213 - f1 0.013812987133860588 - sparse_categorical_accuracy 0.23724888265132904
epoch 21 - batch 20 - loss 2.017590045928955 - precision 0.01920679397881031 - recall 0.01792518049478531 - f1 0.014513778500258923 - sparse_categorical_accuracy 0.23638392984867096
epoch 21 - batch 30 - loss 2.032741069793701 - precision 0.020298058167099953 - recall 0.01810467056930065 - f1 0.015024668537080288 - sparse_categorical_accuracy 0.2360956072807312
epoch 21 - batch 40 - loss 1.9407918453216553 - precision 0.0216272734105587 - recall 0.01835029199719429 - f1 0.015578123740851879 - sparse_categorical_accuracy 0.23703962564468384
epoch 21 - batch 50 - loss 1.9231796264648438 - precision 0.02294822968542576 - recall 0.018709024414420128 - f1 0.01592804118990898 - sparse_categorical_accuracy 0.23695312440395355
epoch 21 - batch 60 - loss 1.9519367218017578 - precision 0.02289789356291294 - recall

wandb: Visualizing heatmap.


epoch 21 evaluation time: 5.590165853500366 sec
epoch evaluation:  {'epoch': 21, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0746744>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.23364526>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.023288198>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.020788621>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.016940838>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 saved checkpoint: models/checkpoints/baseline/ckpt-8
epoch 22 - batch 10 - loss 1.9055567979812622 - precision 0.021019192412495613 - recall 0.020638668909668922 - f1 0.01662236824631691 - sparse_categorical_accuracy 0.23724888265132904
epoch 22 - batch 20 - loss 1.8596869707107544 - precision 0.02273130975663662 - recall 0.0203294325619936 - f1 0.01674257591366768 - sparse_categorical_accuracy 0.2383510023355484
epoch 22 - batch 30 - loss 2.0244994163513184 - precision 0.02467481419444084 - recall 0.020507413893938065 - f1 0.017209704965353012 - sparse_categorical_accuracy 0.2391183078289032
epoch 22 - batch 40 - loss 1.8935195207595825 - precision 0.025581883266568184 - recall 0.0206206776201725 - f1 0.01764880307018757 - sparse_categorical_accuracy 0.23980887234210968
epoch 22 - batch 50 - loss 1.9157582521438599 - precision 0.025687292218208313 - recall 0.020789925009012222 - f1 0.01778740994632244 - sparse_categorical_accuracy 0.23914620280265808
epoch 22 - batch 60 - los

wandb: Visualizing heatmap.


epoch 22 evaluation time: 5.586493492126465 sec
epoch evaluation:  {'epoch': 22, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0683541>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.23361665>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.024034826>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.021241823>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.017583564>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 23 - batch 10 - loss 1.8302326202392578 - precision 0.021810337901115417 - recall 0.02040824107825756 - f1 0.017096128314733505 - sparse_categorical_accuracy 0.23749999701976776
epoch 23 - batch 20 - loss 1.9151204824447632 - precision 0.024093376472592354 - recall 0.02115643583238125 - f1 0.017880922183394432 - sparse_categorical_accuracy 0.23888114094734192
epoch 23 - batch 30 - loss 2.0619149208068848 - precision 0.02501075528562069 - recall 0.021061647683382034 - f1 0.018102150410413742 - sparse_categorical_accuracy 0.23942522704601288
epoch 23 - batch 40 - loss 1.8708096742630005 - precision 0.026276523247361183 - recall 0.021491168066859245 - f1 0.018737439066171646 - sparse_categorical_accuracy 0.2403390109539032
epoch 23 - batch 50 - loss 1.798280954360962 - precision 0.02745559625327587 - recall 0.02183007262647152 - f1 0.01916530728340149 - sparse_categorical_accuracy 0.24047991633415222
epoch 23 - batch 60 - loss 1.9517953395843506 - precision 0.02771894633769989 - rec

wandb: Visualizing heatmap.


epoch 23 evaluation time: 5.587988376617432 sec
epoch evaluation:  {'epoch': 23, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.05127>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.23649983>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.025820024>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.02269383>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.019168684>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 - batch 10 - loss 1.7832000255584717 - precision 0.02367166057229042 - recall 0.021163364872336388 - f1 0.018177179619669914 - sparse_categorical_accuracy 0.24294084310531616
epoch 24 - batch 20 - loss 1.816430926322937 - precision 0.02751833386719227 - recall 0.023482050746679306 - f1 0.020158926025032997 - sparse_categorical_accuracy 0.24282924830913544
epoch 24 - batch 30 - loss 1.8304919004440308 - precision 0.028849110007286072 - recall 0.023519055917859077 - f1 0.020480500534176826 - sparse_categorical_accuracy 0.24310825765132904
epoch 24 - batch 40 - loss 1.7785272598266602 - precision 0.02962123043835163 - recall 0.0235456470400095 - f1 0.02072450891137123 - sparse_categorical_accuracy 0.24355468153953552
epoch 24 - batch 50 - loss 1.8892326354980469 - precision 0.031247202306985855 - recall 0.024051275104284286 - f1 0.021191729232668877 - sparse_categorical_accuracy 0.24318638443946838
epoch 24 - batch 60 - loss 1.8996832370758057 - precision 0.031204745173454285 - r

wandb: Visualizing heatmap.


epoch 24 evaluation time: 5.552903413772583 sec
epoch evaluation:  {'epoch': 24, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0527627>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.23498312>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.027164252>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.023883153>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.019859148>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 saved checkpoint: models/checkpoints/baseline/ckpt-9
epoch 25 - batch 10 - loss 1.8116103410720825 - precision 0.024563370272517204 - recall 0.021997570991516113 - f1 0.018564807251095772 - sparse_categorical_accuracy 0.2416294664144516
epoch 25 - batch 20 - loss 1.8441451787948608 - precision 0.028697019442915916 - recall 0.02444620430469513 - f1 0.02108096331357956 - sparse_categorical_accuracy 0.24362444877624512
epoch 25 - batch 30 - loss 1.8815268278121948 - precision 0.03161069378256798 - recall 0.025292091071605682 - f1 0.022136835381388664 - sparse_categorical_accuracy 0.24435454607009888
epoch 25 - batch 40 - loss 1.8673632144927979 - precision 0.033496253192424774 - recall 0.025618279352784157 - f1 0.022913891822099686 - sparse_categorical_accuracy 0.2450823038816452
epoch 25 - batch 50 - loss 1.8937957286834717 - precision 0.033888962119817734 - recall 0.026006018742918968 - f1 0.023259956389665604 - sparse_categorical_accuracy 0.2451171875
epoch 25 - batch 60 - los

wandb: Visualizing heatmap.


epoch 25 evaluation time: 5.6209986209869385 sec
epoch evaluation:  {'epoch': 25, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0465825>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.23766598>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.031478256>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.025963198>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.022247516>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


Saving checkpoint...
Saved checkpoint: models/checkpoints/baseline/ckpt-10
Done saving model
