<a href="https://colab.research.google.com/github/antonpetkoff/identifier-suggestion/blob/master/notebooks/00-colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# import utilities
import os
import shutil
from subprocess import check_output

In [2]:
!nvidia-smi

Sun Jun 14 14:32:34 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     8W /  75W |      0MiB /  7611MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [4]:
%env WORKSPACE_DIR=/content/gdrive/My Drive/src

# TODO: how can one read an environment variable?!?
%cd '/content/gdrive/My Drive/src'

env: WORKSPACE_DIR=/content/gdrive/My Drive/src
/content/gdrive/My Drive/src


In [0]:
timestamp = check_output(['date', '-u', "+%Y-%m-%dT%H-%M-%S"]).decode('utf-8').strip()

os.environ['PROJECT_DIR'] = os.path.join(
    os.environ['WORKSPACE_DIR'],
    f'identifier-suggestion-{timestamp}',
)

In [6]:
!git clone https://github.com/antonpetkoff/identifier-suggestion.git --depth 1 "${PROJECT_DIR}"

Cloning into '/content/gdrive/My Drive/src/identifier-suggestion-2020-06-14T14-32-36'...
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 100 (delta 1), reused 53 (delta 1), pack-reused 0
Receiving objects: 100% (100/100), 316.99 KiB | 454.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.


In [0]:
os.chdir(os.environ['PROJECT_DIR'])

In [8]:
!pwd
!ls -l

/content/gdrive/My Drive/src/identifier-suggestion-2020-06-14T14-32-36
total 65
drwx------  4 root root  4096 Jun 14 14:32 data
-rw-------  1 root root 35149 Jun 14 14:32 LICENSE
drwx------  2 root root  4096 Jun 14 14:32 notebooks
-rw-------  1 root root  9927 Jun 14 14:32 README.md
drwx------  2 root root  4096 Jun 14 14:32 requirements
drwx------ 13 root root  4096 Jun 14 14:32 src
drwx------  3 root root  4096 Jun 14 14:32 vscode-extension


In [9]:
%tensorflow_version 2.x

import tensorflow
print(tensorflow.__version__)

2.2.0


In [10]:
# Google Colab has standard libraries like numpy, pandas, matplotlib and TF (of course) pre-installed
!pip install -r requirements/colab.txt

In [11]:
# provide secrets to the project, e.g. access to wandb
shutil.copy(
    os.path.join(os.environ['WORKSPACE_DIR'], 'secrets/.env'),
    os.environ['PROJECT_DIR']
)

'/content/gdrive/My Drive/src/identifier-suggestion-2020-06-14T14-32-36/.env'

In [0]:
# monkey-patch (mock) os.symlink to be a noop, because wandb.save() uses it, but it is not supported by Google Colab Notebooks
os.symlink = lambda *x: print('Executing mocked noop symlink with arguments', x)

In [13]:
from argparse import Namespace
from src.pipelines.baseline import run

params = {
  'dir_data': '../data/processed/subtoken/',
  'file_checkpoint_dir': 'models/checkpoints/baseline/',
  'dir_preprocessed_data': '../data/processed/seq2seq/',
  'max_input_length': 200,
  'max_output_length': 8,
  'input_vocab_size': 20000,
  'input_embedding_dim': 50,
  'output_vocab_size': 16000,
  'output_embedding_dim': 50,
  'latent_dim': 320,
  'learning_rate': 0.0001,
  'epochs': 50,
  'batch_size': 256,
  'random_seed': 1,
  'eval_averaging': 'macro'
}

run(Namespace(**params))

Initializing logger


wandb: Wandb version 0.9.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


Experiment parameters:  Namespace(batch_size=256, dir_data='../data/processed/subtoken/', dir_preprocessed_data='../data/processed/seq2seq/', epochs=50, eval_averaging='macro', file_checkpoint_dir='models/checkpoints/baseline/', input_embedding_dim=50, input_vocab_size=20000, latent_dim=320, learning_rate=0.0001, max_input_length=200, max_output_length=8, output_embedding_dim=50, output_vocab_size=16000, random_seed=1)
Loading preprocessed files...
Loaded input vocabulary.
Loaded output vocabulary.
Loaded preprocessed files.
Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
EncoderEmbedding (Embedding) multiple                  1000000   
_________________________________________________________________
EncoderLSTM (LSTM)           multiple                  474880    
Total params: 1,474,880
Trainable params: 1,474,880
Non-trainable params: 0
______________________________________________

wandb: Visualizing heatmap.


epoch 1 evaluation time: 51.03440523147583 sec
epoch evaluation:  {'epoch': 1, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.6472056>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.18958901>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0012924408>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.001259662>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.000962027>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 2 - batch 10 - loss 2.575664520263672 - precision 0.0011329601984471083 - recall 0.001193702220916748 - f1 0.0008906652219593525 - sparse_categorical_accuracy 0.18878348171710968
epoch 2 - batch 20 - loss 2.6015422344207764 - precision 0.0012728822184726596 - recall 0.001239681732840836 - f1 0.0009153904975391924 - sparse_categorical_accuracy 0.18934151530265808
epoch 2 - batch 30 - loss 2.7613024711608887 - precision 0.0013610675232484937 - recall 0.0012449686182662845 - f1 0.000926454842556268 - sparse_categorical_accuracy 0.18869048357009888
epoch 2 - batch 40 - loss 2.5746288299560547 - precision 0.0013729177881032228 - recall 0.0012474614195525646 - f1 0.0009327774168923497 - sparse_categorical_accuracy 0.18885323405265808
epoch 2 - batch 50 - loss 2.745443105697632 - precision 0.0014306247467175126 - recall 0.001254757517017424 - f1 0.0009431100334040821 - sparse_categorical_accuracy 0.18881696462631226
epoch 2 - batch 60 - loss 2.687246084213257 - precision 0.0014657133724

wandb: Visualizing heatmap.


epoch 2 evaluation time: 50.990429162979126 sec
epoch evaluation:  {'epoch': 2, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.4170775>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.20315762>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.006111181>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0040692356>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.003397647>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 - batch 10 - loss 2.3769760131835938 - precision 0.004336895886808634 - recall 0.004018321633338928 - f1 0.0032726461067795753 - sparse_categorical_accuracy 0.20239955186843872
epoch 3 - batch 20 - loss 2.247628688812256 - precision 0.00498685147613287 - recall 0.004020108841359615 - f1 0.003450478659942746 - sparse_categorical_accuracy 0.20273438096046448
epoch 3 - batch 30 - loss 2.4236106872558594 - precision 0.005308511666953564 - recall 0.004102084320038557 - f1 0.0035009148996323347 - sparse_categorical_accuracy 0.2022879421710968
epoch 3 - batch 40 - loss 2.3910324573516846 - precision 0.005578048527240753 - recall 0.004282213281840086 - f1 0.0036633526906371117 - sparse_categorical_accuracy 0.20241349935531616
epoch 3 - batch 50 - loss 2.431140899658203 - precision 0.005808335263282061 - recall 0.0042545790784060955 - f1 0.003640942508354783 - sparse_categorical_accuracy 0.2022767812013626
epoch 3 - batch 60 - loss 2.5464491844177246 - precision 0.005978836212307215 - r

wandb: Visualizing heatmap.


epoch 3 evaluation time: 51.41026592254639 sec
epoch evaluation:  {'epoch': 3, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.2117221>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.21663381>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.018249>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0106228925>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.010251521>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 saved checkpoint: models/checkpoints/baseline/ckpt-2
epoch 4 - batch 10 - loss 2.2095086574554443 - precision 0.010677761398255825 - recall 0.008250117301940918 - f1 0.007821768522262573 - sparse_categorical_accuracy 0.21702009439468384
epoch 4 - batch 20 - loss 2.1834657192230225 - precision 0.012149596586823463 - recall 0.00891915988177061 - f1 0.00837461743503809 - sparse_categorical_accuracy 0.21774554252624512
epoch 4 - batch 30 - loss 2.122307062149048 - precision 0.013336068019270897 - recall 0.00933861918747425 - f1 0.008810901083052158 - sparse_categorical_accuracy 0.21917782723903656
epoch 4 - batch 40 - loss 2.278409242630005 - precision 0.014380218461155891 - recall 0.009847891516983509 - f1 0.009464032016694546 - sparse_categorical_accuracy 0.21788504719734192
epoch 4 - batch 50 - loss 2.233675003051758 - precision 0.014872455038130283 - recall 0.009816218167543411 - f1 0.009546726942062378 - sparse_categorical_accuracy 0.21745535731315613
epoch 4 - batch 60 - loss

wandb: Visualizing heatmap.


epoch 4 evaluation time: 51.287402629852295 sec
epoch evaluation:  {'epoch': 4, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0433345>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2319037>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.033169698>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.019919427>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.01984611>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 5 - batch 10 - loss 1.942160964012146 - precision 0.015703609213232994 - recall 0.012830348685383797 - f1 0.012413198128342628 - sparse_categorical_accuracy 0.2296316921710968
epoch 5 - batch 20 - loss 2.1680588722229004 - precision 0.019474532455205917 - recall 0.015121671371161938 - f1 0.014593925327062607 - sparse_categorical_accuracy 0.23108258843421936
epoch 5 - batch 30 - loss 2.210745096206665 - precision 0.022732779383659363 - recall 0.016463113948702812 - f1 0.016193056479096413 - sparse_categorical_accuracy 0.232328861951828
epoch 5 - batch 40 - loss 2.0026495456695557 - precision 0.024116208776831627 - recall 0.016913091763854027 - f1 0.01679471880197525 - sparse_categorical_accuracy 0.23265904188156128
epoch 5 - batch 50 - loss 2.0193674564361572 - precision 0.025805026292800903 - recall 0.017646873369812965 - f1 0.01764090172946453 - sparse_categorical_accuracy 0.23273438215255737
epoch 5 - batch 60 - loss 1.8711389303207397 - precision 0.027153467759490013 - recall 

wandb: Visualizing heatmap.


epoch 5 evaluation time: 50.47234225273132 sec
epoch evaluation:  {'epoch': 5, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.9110765>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.24595425>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.053864952>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.032406878>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.033429977>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 - batch 10 - loss 1.7708841562271118 - precision 0.023093493655323982 - recall 0.01909332163631916 - f1 0.018870912492275238 - sparse_categorical_accuracy 0.24983258545398712
epoch 6 - batch 20 - loss 1.8675791025161743 - precision 0.029146786779165268 - recall 0.022194184362888336 - f1 0.022440018132328987 - sparse_categorical_accuracy 0.2500278949737549
epoch 6 - batch 30 - loss 1.7903720140457153 - precision 0.03216730058193207 - recall 0.0241684690117836 - f1 0.024593442678451538 - sparse_categorical_accuracy 0.24908854067325592
epoch 6 - batch 40 - loss 1.926405906677246 - precision 0.03574362024664879 - recall 0.02575785107910633 - f1 0.02649744413793087 - sparse_categorical_accuracy 0.24884207546710968
epoch 6 - batch 50 - loss 1.759805679321289 - precision 0.03845259174704552 - recall 0.027235491201281548 - f1 0.027833908796310425 - sparse_categorical_accuracy 0.24925222992897034
epoch 6 - batch 60 - loss 1.950679063796997 - precision 0.040380124002695084 - recall 0.028

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/watchdog/observers/api.py", line 196, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/watchdog/observers/api.py", line 369, in dispatch_events
    handler.dispatch(event)
  File "/usr/local/lib/python3.6/dist-packages/watchdog/events.py", line 452, in dispatch
    super(PatternMatchingEventHandler, self).dispatch(event)
  File "/usr/local/lib/python3.6/dist-packages/watchdog/events.py", line 336, in dispatch
    }[event.event_type](event)
  File "/usr/local/lib/python3.6/dist-packages/wandb/run_manager.py", line 696, in _on_file_modified
    self._get_file_event_handler(event.src_path, save_name).on_modified()
  File "/usr/local/lib/python3.6/dist-packages/wandb/run_manager.py", line 301, in on_modified
    with open(self.file_p

epoch 6 - batch 1070 - loss 1.7091373205184937 - precision 0.07269448041915894 - recall 0.03869452327489853 - f1 0.04167523607611656 - sparse_categorical_accuracy 0.25035515427589417
epoch 6 - batch 1080 - loss 1.5935167074203491 - precision 0.07295800000429153 - recall 0.03876553475856781 - f1 0.04177028685808182 - sparse_categorical_accuracy 0.2503642737865448
epoch 6 - batch 1090 - loss 1.8168284893035889 - precision 0.07325144857168198 - recall 0.038844041526317596 - f1 0.04188455641269684 - sparse_categorical_accuracy 0.25040751695632935
epoch 6 - batch 1100 - loss 1.8282607793807983 - precision 0.07327436655759811 - recall 0.038833342492580414 - f1 0.04187193512916565 - sparse_categorical_accuracy 0.250407874584198
epoch 6 - batch 1110 - loss 1.900730848312378 - precision 0.07358304411172867 - recall 0.03886313736438751 - f1 0.04191312566399574 - sparse_categorical_accuracy 0.2504062056541443
epoch 6 - batch 1120 - loss 1.8983509540557861 - precision 0.07367624342441559 - recall 

wandb: Visualizing heatmap.


epoch 6 evaluation time: 50.566333532333374 sec
epoch evaluation:  {'epoch': 6, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.8105358>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.25755522>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.07721907>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.045855865>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0488181>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 saved checkpoint: models/checkpoints/baseline/ckpt-3
epoch 7 - batch 10 - loss 1.755999207496643 - precision 0.028861453756690025 - recall 0.02374294213950634 - f1 0.023765752092003822 - sparse_categorical_accuracy 0.25758928060531616
epoch 7 - batch 20 - loss 1.6274420022964478 - precision 0.03801990672945976 - recall 0.02984023466706276 - f1 0.030492495745420456 - sparse_categorical_accuracy 0.2610491216182709
epoch 7 - batch 30 - loss 1.8698475360870361 - precision 0.043363891541957855 - recall 0.032945699989795685 - f1 0.033935267478227615 - sparse_categorical_accuracy 0.25972843170166016
epoch 7 - batch 40 - loss 1.8208084106445312 - precision 0.04719847813248634 - recall 0.034715376794338226 - f1 0.03615492209792137 - sparse_categorical_accuracy 0.25989118218421936
epoch 7 - batch 50 - loss 1.714776635169983 - precision 0.0497027188539505 - recall 0.03558909520506859 - f1 0.03729863092303276 - sparse_categorical_accuracy 0.25927454233169556
epoch 7 - batch 60 - loss 1.778

wandb: Visualizing heatmap.


epoch 7 evaluation time: 50.507325410842896 sec
epoch evaluation:  {'epoch': 7, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.7301638>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.26749298>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0968097>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.06235963>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.065452926>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 8 - batch 10 - loss 1.6658731698989868 - precision 0.0330226868391037 - recall 0.028309833258390427 - f1 0.028133103623986244 - sparse_categorical_accuracy 0.27226561307907104
epoch 8 - batch 20 - loss 1.6029866933822632 - precision 0.04430561140179634 - recall 0.03569471091032028 - f1 0.03630274161696434 - sparse_categorical_accuracy 0.2724609375
epoch 8 - batch 30 - loss 1.6739189624786377 - precision 0.053007278591394424 - recall 0.04079299047589302 - f1 0.042182113975286484 - sparse_categorical_accuracy 0.27421873807907104
epoch 8 - batch 40 - loss 1.6801828145980835 - precision 0.058198899030685425 - recall 0.043753210455179214 - f1 0.04540545493364334 - sparse_categorical_accuracy 0.2727818191051483
epoch 8 - batch 50 - loss 1.817173957824707 - precision 0.0630984902381897 - recall 0.04673522338271141 - f1 0.048687390983104706 - sparse_categorical_accuracy 0.27348214387893677
epoch 8 - batch 60 - loss 1.4747593402862549 - precision 0.06768501549959183 - recall 0.04921567812

wandb: Visualizing heatmap.


epoch 8 evaluation time: 51.348811626434326 sec
epoch evaluation:  {'epoch': 8, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.6647997>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2763237>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.11897624>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.07572453>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.081298>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 - batch 10 - loss 1.614427924156189 - precision 0.037783846259117126 - recall 0.032013244926929474 - f1 0.032125018537044525 - sparse_categorical_accuracy 0.2837611734867096
epoch 9 - batch 20 - loss 1.6068168878555298 - precision 0.05172890052199364 - recall 0.04231961816549301 - f1 0.0431019552052021 - sparse_categorical_accuracy 0.2825334966182709
epoch 9 - batch 30 - loss 1.6073577404022217 - precision 0.062262412160634995 - recall 0.050034694373607635 - f1 0.0511687807738781 - sparse_categorical_accuracy 0.28454241156578064
epoch 9 - batch 40 - loss 1.5019253492355347 - precision 0.06950359791517258 - recall 0.05354452505707741 - f1 0.055558253079652786 - sparse_categorical_accuracy 0.28549107909202576
epoch 9 - batch 50 - loss 1.5113898515701294 - precision 0.07713225483894348 - recall 0.05812728404998779 - f1 0.06095800921320915 - sparse_categorical_accuracy 0.28533482551574707
epoch 9 - batch 60 - loss 1.5000264644622803 - precision 0.08224981278181076 - recall 0.061146

wandb: Visualizing heatmap.


epoch 9 evaluation time: 51.17260241508484 sec
epoch evaluation:  {'epoch': 9, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.62505>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.28213596>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.1342928>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.08939417>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.09545662>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 saved checkpoint: models/checkpoints/baseline/ckpt-4
epoch 10 - batch 10 - loss 1.3105781078338623 - precision 0.04115079715847969 - recall 0.03641229122877121 - f1 0.035952240228652954 - sparse_categorical_accuracy 0.2904575765132904
epoch 10 - batch 20 - loss 1.552323341369629 - precision 0.05804692581295967 - recall 0.04908522590994835 - f1 0.04942850023508072 - sparse_categorical_accuracy 0.29232701659202576
epoch 10 - batch 30 - loss 1.6010000705718994 - precision 0.07027643173933029 - recall 0.05688999220728874 - f1 0.058211538940668106 - sparse_categorical_accuracy 0.2917782664299011
epoch 10 - batch 40 - loss 1.5561059713363647 - precision 0.07902210205793381 - recall 0.06212088465690613 - f1 0.06430204957723618 - sparse_categorical_accuracy 0.2904575765132904
epoch 10 - batch 50 - loss 1.538233757019043 - precision 0.0860464945435524 - recall 0.06669175624847412 - f1 0.06938133388757706 - sparse_categorical_accuracy 0.2904687523841858
epoch 10 - batch 60 - loss 1.55861

wandb: Visualizing heatmap.


epoch 10 evaluation time: 50.35795068740845 sec
epoch evaluation:  {'epoch': 10, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.5786965>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.28919658>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.14829198>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.10095011>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.10787024>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 11 - batch 10 - loss 1.3735018968582153 - precision 0.04483691602945328 - recall 0.03972833976149559 - f1 0.03966781124472618 - sparse_categorical_accuracy 0.3021763265132904
epoch 11 - batch 20 - loss 1.3713891506195068 - precision 0.06486287713050842 - recall 0.05493815243244171 - f1 0.055902350693941116 - sparse_categorical_accuracy 0.3012276887893677
epoch 11 - batch 30 - loss 1.539833664894104 - precision 0.07854343205690384 - recall 0.06495708227157593 - f1 0.06667304784059525 - sparse_categorical_accuracy 0.30074405670166016
epoch 11 - batch 40 - loss 1.4040671586990356 - precision 0.08776110410690308 - recall 0.0706600546836853 - f1 0.07322452962398529 - sparse_categorical_accuracy 0.3004603683948517
epoch 11 - batch 50 - loss 1.4052423238754272 - precision 0.09661167860031128 - recall 0.0766584649682045 - f1 0.07988453656435013 - sparse_categorical_accuracy 0.3010267913341522
epoch 11 - batch 60 - loss 1.356099247932434 - precision 0.10388018190860748 - recall 0.08171116

wandb: Visualizing heatmap.


epoch 11 evaluation time: 51.20527124404907 sec
epoch evaluation:  {'epoch': 11, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.540922>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.29463562>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.16384713>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.113097586>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.12102992>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 - batch 10 - loss 1.4467275142669678 - precision 0.04906359687447548 - recall 0.04324880987405777 - f1 0.04320977255702019 - sparse_categorical_accuracy 0.30809152126312256
epoch 12 - batch 20 - loss 1.4067878723144531 - precision 0.06943627446889877 - recall 0.059369564056396484 - f1 0.06031070649623871 - sparse_categorical_accuracy 0.30867746472358704
epoch 12 - batch 30 - loss 1.373355746269226 - precision 0.0864175483584404 - recall 0.07243422418832779 - f1 0.07426764070987701 - sparse_categorical_accuracy 0.3114769458770752
epoch 12 - batch 40 - loss 1.5090692043304443 - precision 0.09810466319322586 - recall 0.0818847045302391 - f1 0.08392346650362015 - sparse_categorical_accuracy 0.31032365560531616
epoch 12 - batch 50 - loss 1.4790446758270264 - precision 0.10838652402162552 - recall 0.08893978595733643 - f1 0.09150321781635284 - sparse_categorical_accuracy 0.30989953875541687
epoch 12 - batch 60 - loss 1.204577088356018 - precision 0.11588800698518753 - recall 0.09382

wandb: Visualizing heatmap.


epoch 12 evaluation time: 50.85849666595459 sec
epoch evaluation:  {'epoch': 12, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.515629>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2988082>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.16851294>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.12347363>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.12984788>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 saved checkpoint: models/checkpoints/baseline/ckpt-5
epoch 13 - batch 10 - loss 1.228812336921692 - precision 0.05098514258861542 - recall 0.045926932245492935 - f1 0.045569032430648804 - sparse_categorical_accuracy 0.3178013265132904
epoch 13 - batch 20 - loss 1.2227154970169067 - precision 0.07654646784067154 - recall 0.06600361317396164 - f1 0.06670881062746048 - sparse_categorical_accuracy 0.3191964328289032
epoch 13 - batch 30 - loss 1.3866701126098633 - precision 0.09209262579679489 - recall 0.07816854119300842 - f1 0.07980795949697495 - sparse_categorical_accuracy 0.31690847873687744
epoch 13 - batch 40 - loss 1.2323100566864014 - precision 0.10380947589874268 - recall 0.08616333454847336 - f1 0.0887204185128212 - sparse_categorical_accuracy 0.3153599202632904
epoch 13 - batch 50 - loss 1.287947654724121 - precision 0.11576872318983078 - recall 0.09542325139045715 - f1 0.09860125929117203 - sparse_categorical_accuracy 0.3154129385948181
epoch 13 - batch 60 - loss 1.2401

wandb: Visualizing heatmap.


epoch 13 evaluation time: 50.62593221664429 sec
epoch evaluation:  {'epoch': 13, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4954001>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.30246443>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.17647432>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.13176055>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.13771385>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 14 - batch 10 - loss 1.1908913850784302 - precision 0.055432625114917755 - recall 0.050053663551807404 - f1 0.04980708658695221 - sparse_categorical_accuracy 0.3193638324737549
epoch 14 - batch 20 - loss 1.3061189651489258 - precision 0.07789577543735504 - recall 0.06840262562036514 - f1 0.0691673755645752 - sparse_categorical_accuracy 0.3211495578289032
epoch 14 - batch 30 - loss 1.3000684976577759 - precision 0.09720168262720108 - recall 0.0826190784573555 - f1 0.0844946876168251 - sparse_categorical_accuracy 0.32083332538604736
epoch 14 - batch 40 - loss 1.280442476272583 - precision 0.11001382023096085 - recall 0.09226012974977493 - f1 0.09483245015144348 - sparse_categorical_accuracy 0.32113561034202576
epoch 14 - batch 50 - loss 1.1846038103103638 - precision 0.1203136295080185 - recall 0.10040661692619324 - f1 0.10337700694799423 - sparse_categorical_accuracy 0.320904016494751
epoch 14 - batch 60 - loss 1.3196942806243896 - precision 0.12919831275939941 - recall 0.10702892

wandb: Visualizing heatmap.


epoch 14 evaluation time: 52.351439476013184 sec
epoch evaluation:  {'epoch': 14, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4786556>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.30559883>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.18366596>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.13639933>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.14371717>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 - batch 10 - loss 1.291560411453247 - precision 0.057156335562467575 - recall 0.05210087075829506 - f1 0.051803167909383774 - sparse_categorical_accuracy 0.32650670409202576
epoch 15 - batch 20 - loss 1.1044862270355225 - precision 0.08286632597446442 - recall 0.07315805554389954 - f1 0.07374618947505951 - sparse_categorical_accuracy 0.32695311307907104
epoch 15 - batch 30 - loss 1.0932939052581787 - precision 0.0985448881983757 - recall 0.08506213128566742 - f1 0.08658332377672195 - sparse_categorical_accuracy 0.3257998526096344
epoch 15 - batch 40 - loss 1.254475474357605 - precision 0.11452587693929672 - recall 0.09735818207263947 - f1 0.0997692197561264 - sparse_categorical_accuracy 0.32660436630249023
epoch 15 - batch 50 - loss 1.1745507717132568 - precision 0.12770295143127441 - recall 0.10725238174200058 - f1 0.11037056148052216 - sparse_categorical_accuracy 0.32683035731315613
epoch 15 - batch 60 - loss 1.2254610061645508 - precision 0.13659420609474182 - recall 0.1141

wandb: Visualizing heatmap.


epoch 15 evaluation time: 52.17635750770569 sec
epoch evaluation:  {'epoch': 15, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4718708>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.30670223>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.18783689>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.13936414>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.14742748>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 saved checkpoint: models/checkpoints/baseline/ckpt-6
epoch 16 - batch 10 - loss 1.1702239513397217 - precision 0.05756348744034767 - recall 0.05260578542947769 - f1 0.05224604532122612 - sparse_categorical_accuracy 0.33041295409202576
epoch 16 - batch 20 - loss 1.1605643033981323 - precision 0.08505580574274063 - recall 0.07575441151857376 - f1 0.07587838172912598 - sparse_categorical_accuracy 0.3289899528026581
epoch 16 - batch 30 - loss 1.079132318496704 - precision 0.10590968281030655 - recall 0.0911574587225914 - f1 0.09303116053342819 - sparse_categorical_accuracy 0.32966890931129456
epoch 16 - batch 40 - loss 1.2564364671707153 - precision 0.1211552768945694 - recall 0.10338440537452698 - f1 0.1058044582605362 - sparse_categorical_accuracy 0.3301897346973419
epoch 16 - batch 50 - loss 1.2150475978851318 - precision 0.13412344455718994 - recall 0.11339976638555527 - f1 0.11650540679693222 - sparse_categorical_accuracy 0.3306138515472412
epoch 16 - batch 60 - loss 1.244743

wandb: Visualizing heatmap.


epoch 16 evaluation time: 51.33527731895447 sec
epoch evaluation:  {'epoch': 16, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.45789>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.30957755>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.19221942>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.14604115>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.15319291>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 17 - batch 10 - loss 1.1745504140853882 - precision 0.060019511729478836 - recall 0.05499737337231636 - f1 0.05473359301686287 - sparse_categorical_accuracy 0.3337053656578064
epoch 17 - batch 20 - loss 1.1943838596343994 - precision 0.0890420600771904 - recall 0.078373484313488 - f1 0.07912338525056839 - sparse_categorical_accuracy 0.33337053656578064
epoch 17 - batch 30 - loss 1.334768295288086 - precision 0.10813643038272858 - recall 0.0940326452255249 - f1 0.09556901454925537 - sparse_categorical_accuracy 0.333798348903656
epoch 17 - batch 40 - loss 1.195239782333374 - precision 0.12341704964637756 - recall 0.10627277940511703 - f1 0.10851284116506577 - sparse_categorical_accuracy 0.3351981043815613
epoch 17 - batch 50 - loss 1.0461480617523193 - precision 0.13681377470493317 - recall 0.11694426834583282 - f1 0.11977750062942505 - sparse_categorical_accuracy 0.3353906273841858
epoch 17 - batch 60 - loss 1.176506757736206 - precision 0.1481015682220459 - recall 0.1264689564704

wandb: Visualizing heatmap.


epoch 17 evaluation time: 50.517377853393555 sec
epoch evaluation:  {'epoch': 17, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4465038>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31178433>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.19542949>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.15128475>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.15773433>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 - batch 10 - loss 1.0940821170806885 - precision 0.06468521058559418 - recall 0.05999723821878433 - f1 0.059325460344552994 - sparse_categorical_accuracy 0.34296876192092896
epoch 18 - batch 20 - loss 1.224911093711853 - precision 0.09121720492839813 - recall 0.08161238580942154 - f1 0.08199967443943024 - sparse_categorical_accuracy 0.3384207487106323
epoch 18 - batch 30 - loss 1.1622250080108643 - precision 0.11018183827400208 - recall 0.0968884527683258 - f1 0.09833306819200516 - sparse_categorical_accuracy 0.33653274178504944
epoch 18 - batch 40 - loss 1.1264182329177856 - precision 0.12715519964694977 - recall 0.11048436164855957 - f1 0.11272618919610977 - sparse_categorical_accuracy 0.3372907340526581
epoch 18 - batch 50 - loss 1.2058541774749756 - precision 0.14007721841335297 - recall 0.12088248878717422 - f1 0.12349209934473038 - sparse_categorical_accuracy 0.3384151756763458
epoch 18 - batch 60 - loss 1.1889714002609253 - precision 0.15159155428409576 - recall 0.13003

wandb: Visualizing heatmap.


epoch 18 evaluation time: 50.64197254180908 sec
epoch evaluation:  {'epoch': 18, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4439994>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31301093>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.19875005>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.15272076>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.16030024>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 saved checkpoint: models/checkpoints/baseline/ckpt-7
epoch 19 - batch 10 - loss 1.1220468282699585 - precision 0.06531435251235962 - recall 0.06015541031956673 - f1 0.05971077084541321 - sparse_categorical_accuracy 0.3461495637893677
epoch 19 - batch 20 - loss 1.1517335176467896 - precision 0.09196240454912186 - recall 0.08255095779895782 - f1 0.08288070559501648 - sparse_categorical_accuracy 0.34408482909202576
epoch 19 - batch 30 - loss 1.161281943321228 - precision 0.11183787137269974 - recall 0.09972517937421799 - f1 0.10075046867132187 - sparse_categorical_accuracy 0.3432663679122925
epoch 19 - batch 40 - loss 1.1160064935684204 - precision 0.1292179673910141 - recall 0.11349599808454514 - f1 0.1153465136885643 - sparse_categorical_accuracy 0.3433593809604645
epoch 19 - batch 50 - loss 1.1745365858078003 - precision 0.1421665996313095 - recall 0.12380053848028183 - f1 0.12618502974510193 - sparse_categorical_accuracy 0.3441517949104309
epoch 19 - batch 60 - loss 1.1367274

wandb: Visualizing heatmap.


epoch 19 evaluation time: 50.76251673698425 sec
epoch evaluation:  {'epoch': 19, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4350917>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31430817>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.2011345>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.15711863>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.16412205>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 20 - batch 10 - loss 1.241065263748169 - precision 0.0669722780585289 - recall 0.06151491031050682 - f1 0.06145143881440163 - sparse_categorical_accuracy 0.34966516494750977
epoch 20 - batch 20 - loss 1.1111738681793213 - precision 0.09467244893312454 - recall 0.0850747674703598 - f1 0.08576512336730957 - sparse_categorical_accuracy 0.3472098112106323
epoch 20 - batch 30 - loss 1.0250587463378906 - precision 0.11626425385475159 - recall 0.10301608592271805 - f1 0.10438302904367447 - sparse_categorical_accuracy 0.3470982015132904
epoch 20 - batch 40 - loss 1.1463323831558228 - precision 0.13081039488315582 - recall 0.11490916460752487 - f1 0.11686459183692932 - sparse_categorical_accuracy 0.3460100591182709
epoch 20 - batch 50 - loss 1.0387877225875854 - precision 0.1461891084909439 - recall 0.128292515873909 - f1 0.13063712418079376 - sparse_categorical_accuracy 0.3469531238079071
epoch 20 - batch 60 - loss 1.0670037269592285 - precision 0.15882888436317444 - recall 0.13879136741

wandb: Visualizing heatmap.


epoch 20 evaluation time: 50.69556260108948 sec
epoch evaluation:  {'epoch': 20, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4337511>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31586272>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20281082>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.15831272>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.16573063>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 - batch 10 - loss 1.0489994287490845 - precision 0.06720935553312302 - recall 0.06253267079591751 - f1 0.061991024762392044 - sparse_categorical_accuracy 0.3508928716182709
epoch 21 - batch 20 - loss 0.9530596733093262 - precision 0.0963878482580185 - recall 0.08709411323070526 - f1 0.08743534982204437 - sparse_categorical_accuracy 0.3480747640132904
epoch 21 - batch 30 - loss 1.0097590684890747 - precision 0.1172930970788002 - recall 0.10501214861869812 - f1 0.10588886588811874 - sparse_categorical_accuracy 0.3486793041229248
epoch 21 - batch 40 - loss 0.9925387501716614 - precision 0.13389016687870026 - recall 0.11836674064397812 - f1 0.12011947482824326 - sparse_categorical_accuracy 0.3493582606315613
epoch 21 - batch 50 - loss 0.9101139307022095 - precision 0.1507239192724228 - recall 0.13252179324626923 - f1 0.1348823755979538 - sparse_categorical_accuracy 0.35064733028411865
epoch 21 - batch 60 - loss 1.17589271068573 - precision 0.16252538561820984 - recall 0.1425888389

wandb: Visualizing heatmap.


epoch 21 evaluation time: 53.417468309402466 sec
epoch evaluation:  {'epoch': 21, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4319018>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3163845>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20236063>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16218749>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.16772768>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 saved checkpoint: models/checkpoints/baseline/ckpt-8
epoch 22 - batch 10 - loss 1.0887069702148438 - precision 0.06808590888977051 - recall 0.06262098997831345 - f1 0.062333304435014725 - sparse_categorical_accuracy 0.3537946343421936
epoch 22 - batch 20 - loss 1.1176718473434448 - precision 0.0970248281955719 - recall 0.08667770028114319 - f1 0.0875597819685936 - sparse_categorical_accuracy 0.35122767090797424
epoch 22 - batch 30 - loss 1.0149699449539185 - precision 0.11932510137557983 - recall 0.10703403502702713 - f1 0.10794860124588013 - sparse_categorical_accuracy 0.3510974645614624
epoch 22 - batch 40 - loss 1.1124736070632935 - precision 0.13901282846927643 - recall 0.12329795956611633 - f1 0.12530985474586487 - sparse_categorical_accuracy 0.3517717719078064
epoch 22 - batch 50 - loss 1.0811529159545898 - precision 0.15464431047439575 - recall 0.13689181208610535 - f1 0.139192596077919 - sparse_categorical_accuracy 0.3521205484867096
epoch 22 - batch 60 - loss 1.016653

wandb: Visualizing heatmap.


epoch 22 evaluation time: 51.377015352249146 sec
epoch evaluation:  {'epoch': 22, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4277118>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31758392>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20429371>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16350019>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.16939403>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 23 - batch 10 - loss 1.0029683113098145 - precision 0.06836424022912979 - recall 0.062559574842453 - f1 0.06257040798664093 - sparse_categorical_accuracy 0.3559151887893677
epoch 23 - batch 20 - loss 1.146418571472168 - precision 0.09674070030450821 - recall 0.08793295919895172 - f1 0.08836115151643753 - sparse_categorical_accuracy 0.3525669574737549
epoch 23 - batch 30 - loss 1.097840666770935 - precision 0.12074334174394608 - recall 0.10842455178499222 - f1 0.10947409272193909 - sparse_categorical_accuracy 0.35252976417541504
epoch 23 - batch 40 - loss 1.0517327785491943 - precision 0.1369691640138626 - recall 0.12204433977603912 - f1 0.12358563393354416 - sparse_categorical_accuracy 0.35231584310531616
epoch 23 - batch 50 - loss 1.0480729341506958 - precision 0.1551254242658615 - recall 0.13803371787071228 - f1 0.13996325433254242 - sparse_categorical_accuracy 0.35484373569488525
epoch 23 - batch 60 - loss 1.0259522199630737 - precision 0.16887272894382477 - recall 0.149987712

wandb: Visualizing heatmap.


epoch 23 evaluation time: 50.93884634971619 sec
epoch evaluation:  {'epoch': 23, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4260713>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3180749>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.2034875>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16463087>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.17011732>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 - batch 10 - loss 0.9160817265510559 - precision 0.06953176856040955 - recall 0.06405885517597198 - f1 0.06377939134836197 - sparse_categorical_accuracy 0.3572544753551483
epoch 24 - batch 20 - loss 1.187044382095337 - precision 0.0985456332564354 - recall 0.08897475153207779 - f1 0.08949236571788788 - sparse_categorical_accuracy 0.35552453994750977
epoch 24 - batch 30 - loss 1.0307626724243164 - precision 0.12264921516180038 - recall 0.11016441136598587 - f1 0.11117427051067352 - sparse_categorical_accuracy 0.3569382429122925
epoch 24 - batch 40 - loss 1.059165596961975 - precision 0.14243026077747345 - recall 0.1277543306350708 - f1 0.12925651669502258 - sparse_categorical_accuracy 0.35708704590797424
epoch 24 - batch 50 - loss 1.1241950988769531 - precision 0.1584322154521942 - recall 0.14080852270126343 - f1 0.1430739015340805 - sparse_categorical_accuracy 0.35724329948425293
epoch 24 - batch 60 - loss 1.077865719795227 - precision 0.17214959859848022 - recall 0.1528434157

wandb: Visualizing heatmap.


epoch 24 evaluation time: 51.00984239578247 sec
epoch evaluation:  {'epoch': 24, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.426717>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3188377>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20486596>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16654652>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.17176135>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 saved checkpoint: models/checkpoints/baseline/ckpt-9
epoch 25 - batch 10 - loss 0.9583860635757446 - precision 0.07162759453058243 - recall 0.06598476320505142 - f1 0.06582586467266083 - sparse_categorical_accuracy 0.3634486496448517
epoch 25 - batch 20 - loss 0.9704307913780212 - precision 0.10279998183250427 - recall 0.0937170758843422 - f1 0.09398266673088074 - sparse_categorical_accuracy 0.3596819341182709
epoch 25 - batch 30 - loss 1.000458836555481 - precision 0.12485922873020172 - recall 0.11258671432733536 - f1 0.11353448778390884 - sparse_categorical_accuracy 0.3593935966491699
epoch 25 - batch 40 - loss 0.9879843592643738 - precision 0.14342734217643738 - recall 0.12870530784130096 - f1 0.1301119476556778 - sparse_categorical_accuracy 0.3590680658817291
epoch 25 - batch 50 - loss 1.129312515258789 - precision 0.1598900556564331 - recall 0.1429252177476883 - f1 0.14458592236042023 - sparse_categorical_accuracy 0.359386146068573
epoch 25 - batch 60 - loss 1.05305588245

wandb: Visualizing heatmap.


epoch 25 evaluation time: 51.27612113952637 sec
epoch evaluation:  {'epoch': 25, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4289248>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31945914>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20837204>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16674311>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.17363359>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 26 - batch 10 - loss 1.0644845962524414 - precision 0.06846535205841064 - recall 0.06334078311920166 - f1 0.06323409080505371 - sparse_categorical_accuracy 0.3626116216182709
epoch 26 - batch 20 - loss 0.9432440400123596 - precision 0.10213690251111984 - recall 0.09247849136590958 - f1 0.09287456423044205 - sparse_categorical_accuracy 0.36040735244750977
epoch 26 - batch 30 - loss 1.0216354131698608 - precision 0.12551739811897278 - recall 0.11275758594274521 - f1 0.11390382796525955 - sparse_categorical_accuracy 0.3600074350833893
epoch 26 - batch 40 - loss 0.9044523239135742 - precision 0.1448362022638321 - recall 0.1306186020374298 - f1 0.13207557797431946 - sparse_categorical_accuracy 0.36169084906578064
epoch 26 - batch 50 - loss 0.9791857004165649 - precision 0.16269834339618683 - recall 0.14630118012428284 - f1 0.1481485664844513 - sparse_categorical_accuracy 0.3628348112106323
epoch 26 - batch 60 - loss 0.969985842704773 - precision 0.17661388218402863 - recall 0.15857036

wandb: Visualizing heatmap.


epoch 26 evaluation time: 52.338603496551514 sec
epoch evaluation:  {'epoch': 26, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4263793>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.32007334>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20570958>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16864721>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.17351383>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 27 - batch 10 - loss 0.9668779373168945 - precision 0.0713680163025856 - recall 0.0667765662074089 - f1 0.06629811972379684 - sparse_categorical_accuracy 0.36462053656578064
epoch 27 - batch 20 - loss 0.9428107142448425 - precision 0.10413233190774918 - recall 0.09500408917665482 - f1 0.09545750170946121 - sparse_categorical_accuracy 0.36503905057907104
epoch 27 - batch 30 - loss 1.143860936164856 - precision 0.12797309458255768 - recall 0.11628252267837524 - f1 0.11690866202116013 - sparse_categorical_accuracy 0.3648437559604645
epoch 27 - batch 40 - loss 0.8899162411689758 - precision 0.14768683910369873 - recall 0.13325026631355286 - f1 0.13450203835964203 - sparse_categorical_accuracy 0.36329519748687744
epoch 27 - batch 50 - loss 1.004158616065979 - precision 0.16518442332744598 - recall 0.14952339231967926 - f1 0.15098837018013 - sparse_categorical_accuracy 0.3641406297683716
epoch 27 - batch 60 - loss 1.0450865030288696 - precision 0.1789679080247879 - recall 0.16120870411

wandb: Visualizing heatmap.


epoch 27 evaluation time: 51.39547848701477 sec
epoch evaluation:  {'epoch': 27, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4310726>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.319932>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.20734774>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.16866793>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.17430505>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


ValueError: ignored