<a href="https://colab.research.google.com/github/antonpetkoff/identifier-suggestion/blob/master/notebooks/00-colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import utilities
import os
import shutil
from subprocess import check_output

In [2]:
!nvidia-smi

Tue Jun 23 17:12:55 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [4]:
%env WORKSPACE_DIR=/content/gdrive/My Drive/src

# TODO: how can one read an environment variable?!?
%cd '/content/gdrive/My Drive/src'

env: WORKSPACE_DIR=/content/gdrive/My Drive/src
/content/gdrive/My Drive/src


In [5]:
timestamp = check_output(['date', '-u', "+%Y-%m-%dT%H-%M-%S"]).decode('utf-8').strip()

os.environ['PROJECT_DIR'] = os.path.join(
    os.environ['WORKSPACE_DIR'],
    f'identifier-suggestion-{timestamp}',
)

In [6]:
!git clone https://github.com/antonpetkoff/identifier-suggestion.git --depth 1 "${PROJECT_DIR}"

Cloning into '/content/gdrive/My Drive/src/identifier-suggestion-2020-06-23T17-12-57'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 106 (delta 1), reused 62 (delta 1), pack-reused 0
Receiving objects: 100% (106/106), 925.64 KiB | 2.43 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [7]:
os.chdir(os.environ['PROJECT_DIR'])

In [8]:
!pwd
!ls -l

/content/gdrive/My Drive/src/identifier-suggestion-2020-06-23T17-12-57
total 69
drwx------  4 root root  4096 Jun 23 17:13 data
-rw-------  1 root root 35149 Jun 23 17:13 LICENSE
drwx------  2 root root  4096 Jun 23 17:13 notebooks
-rw-------  1 root root 10022 Jun 23 17:13 README.md
drwx------  3 root root  4096 Jun 23 17:13 reports
drwx------  2 root root  4096 Jun 23 17:13 requirements
drwx------ 13 root root  4096 Jun 23 17:13 src
drwx------  3 root root  4096 Jun 23 17:13 vscode-extension


In [9]:
%tensorflow_version 2.x

import tensorflow
print(tensorflow.__version__)

2.2.0


In [10]:
# Google Colab has standard libraries like numpy, pandas, matplotlib and TF (of course) pre-installed
!pip install -r requirements/colab.txt

In [11]:
# provide secrets to the project, e.g. access to wandb
shutil.copy(
    os.path.join(os.environ['WORKSPACE_DIR'], 'secrets/.env'),
    os.environ['PROJECT_DIR']
)

'/content/gdrive/My Drive/src/identifier-suggestion-2020-06-23T17-12-57/.env'

In [12]:
# monkey-patch (mock) os.symlink to be a noop, because wandb.save() uses it, but it is not supported by Google Colab Notebooks
os.symlink = lambda *x: print('Executing mocked noop symlink with arguments', x)

In [13]:
from argparse import Namespace
from src.pipelines.baseline import run

params = {
  'dir_data': '../data/processed/subtoken/',
  'file_checkpoint_dir': 'models/checkpoints/baseline/',
  'dir_preprocessed_data': '../data/processed/seq2seq/',
  'max_input_length': 128,
  'max_output_length': 8,
  'input_vocab_size': 5000,
  'input_embedding_dim': 50,
  'output_vocab_size': 5000,
  'output_embedding_dim': 50,
  'latent_dim': 320,
  'learning_rate': 0.0001,
  'epochs': 50,
  'batch_size': 512,
  'random_seed': 1,
  'eval_averaging': 'macro'
}

run(Namespace(**params))

Initializing logger


wandb: Wandb version 0.9.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


Experiment parameters:  Namespace(batch_size=512, dir_data='../data/processed/subtoken/', dir_preprocessed_data='../data/processed/seq2seq/', epochs=50, eval_averaging='macro', file_checkpoint_dir='models/checkpoints/baseline/', input_embedding_dim=50, input_vocab_size=5000, latent_dim=320, learning_rate=0.0001, max_input_length=128, max_output_length=8, output_embedding_dim=50, output_vocab_size=5000, random_seed=1)
Loading preprocessed files...
Loaded input vocabulary.
Loaded output vocabulary.
Loaded preprocessed files.
Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
EncoderEmbedding (Embedding) multiple                  250000    
_________________________________________________________________
EncoderLSTM (LSTM)           multiple                  474880    
Total params: 724,880
Trainable params: 724,880
Non-trainable params: 0
____________________________________________________

wandb: Visualizing heatmap.


epoch 1 evaluation time: 15.656538963317871 sec
epoch evaluation:  {'epoch': 1, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.6153462>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.1892955>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0038432572>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0037997449>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0028390968>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 2 - batch 10 - loss 2.5918757915496826 - precision 0.0033368945587426424 - recall 0.003786233486607671 - f1 0.0027842968702316284 - sparse_categorical_accuracy 0.18872767686843872
epoch 2 - batch 20 - loss 2.579091787338257 - precision 0.0034139174968004227 - recall 0.003877338720485568 - f1 0.0029128724709153175 - sparse_categorical_accuracy 0.1884068101644516
epoch 2 - batch 30 - loss 2.7466907501220703 - precision 0.0037020831368863583 - recall 0.0038973393384367228 - f1 0.0028547453694045544 - sparse_categorical_accuracy 0.18822544813156128
epoch 2 - batch 40 - loss 2.7223541736602783 - precision 0.00377863016910851 - recall 0.003871023887768388 - f1 0.0028231434989720583 - sparse_categorical_accuracy 0.1887904554605484
epoch 2 - batch 50 - loss 2.5655558109283447 - precision 0.004278489854186773 - recall 0.0039147580973804 - f1 0.0028690833132714033 - sparse_categorical_accuracy 0.18872767686843872
epoch 2 - batch 60 - loss 2.5592122077941895 - precision 0.004311444237828255

wandb: Visualizing heatmap.


epoch 2 evaluation time: 16.145979404449463 sec
epoch evaluation:  {'epoch': 2, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.3630483>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.20482084>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.02337263>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.014215349>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0128394915>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 - batch 10 - loss 2.3319995403289795 - precision 0.019061820581555367 - recall 0.013188120909035206 - f1 0.012172960676252842 - sparse_categorical_accuracy 0.2047991007566452
epoch 3 - batch 20 - loss 2.386375665664673 - precision 0.019982418045401573 - recall 0.013683448545634747 - f1 0.012372356839478016 - sparse_categorical_accuracy 0.20485490560531616
epoch 3 - batch 30 - loss 2.4729855060577393 - precision 0.021391497924923897 - recall 0.013529756106436253 - f1 0.012339837849140167 - sparse_categorical_accuracy 0.2044735848903656
epoch 3 - batch 40 - loss 2.301118850708008 - precision 0.022483909502625465 - recall 0.013790800236165524 - f1 0.012701532803475857 - sparse_categorical_accuracy 0.20489676296710968
epoch 3 - batch 50 - loss 2.424565553665161 - precision 0.023274783045053482 - recall 0.014016161672770977 - f1 0.013078788295388222 - sparse_categorical_accuracy 0.20447544753551483
epoch 3 - batch 60 - loss 2.388526439666748 - precision 0.023769032210111618 - recall

wandb: Visualizing heatmap.


epoch 3 evaluation time: 16.189331531524658 sec
epoch evaluation:  {'epoch': 3, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0999773>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.22523083>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.08010802>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.040284697>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.041827347>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 saved checkpoint: models/checkpoints/baseline/ckpt-2
epoch 4 - batch 10 - loss 2.1095688343048096 - precision 0.05228718742728233 - recall 0.036355480551719666 - f1 0.03673819452524185 - sparse_categorical_accuracy 0.22625558078289032
epoch 4 - batch 20 - loss 2.231687545776367 - precision 0.06022860109806061 - recall 0.038668058812618256 - f1 0.039308562874794006 - sparse_categorical_accuracy 0.22575335204601288
epoch 4 - batch 30 - loss 2.0355961322784424 - precision 0.06396494060754776 - recall 0.03901563957333565 - f1 0.04011956974864006 - sparse_categorical_accuracy 0.22541852295398712
epoch 4 - batch 40 - loss 2.15915846824646 - precision 0.06775417178869247 - recall 0.03990129381418228 - f1 0.041236963123083115 - sparse_categorical_accuracy 0.22540457546710968
epoch 4 - batch 50 - loss 2.0526483058929443 - precision 0.0707642063498497 - recall 0.04007045552134514 - f1 0.04178236052393913 - sparse_categorical_accuracy 0.2253292351961136
epoch 4 - batch 60 - loss 1.9311977

wandb: Visualizing heatmap.


epoch 4 evaluation time: 15.666601181030273 sec
epoch evaluation:  {'epoch': 4, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.8760035>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.24695073>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.16014056>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.08178849>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.08938047>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 5 - batch 10 - loss 1.8649834394454956 - precision 0.09472940862178802 - recall 0.06573852896690369 - f1 0.06848468631505966 - sparse_categorical_accuracy 0.24620535969734192
epoch 5 - batch 20 - loss 1.7851251363754272 - precision 0.11529441922903061 - recall 0.07377051562070847 - f1 0.07924055308103561 - sparse_categorical_accuracy 0.24711216986179352
epoch 5 - batch 30 - loss 1.8254972696304321 - precision 0.12396612763404846 - recall 0.07636137306690216 - f1 0.08266230672597885 - sparse_categorical_accuracy 0.246186763048172
epoch 5 - batch 40 - loss 1.8468968868255615 - precision 0.13175855576992035 - recall 0.07775353640317917 - f1 0.08490552753210068 - sparse_categorical_accuracy 0.24716797471046448
epoch 5 - batch 50 - loss 1.7505772113800049 - precision 0.1396072506904602 - recall 0.07878880202770233 - f1 0.08730988949537277 - sparse_categorical_accuracy 0.24753348529338837
epoch 5 - batch 60 - loss 1.8663932085037231 - precision 0.14451837539672852 - recall 0.0794811397

wandb: Visualizing heatmap.


epoch 5 evaluation time: 16.024304151535034 sec
epoch evaluation:  {'epoch': 5, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.7194731>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2652409>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.25538749>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.12929939>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.14735499>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 - batch 10 - loss 1.7130223512649536 - precision 0.1282961368560791 - recall 0.09624255448579788 - f1 0.09946674108505249 - sparse_categorical_accuracy 0.26693639159202576
epoch 6 - batch 20 - loss 1.8010109663009644 - precision 0.16346363723278046 - recall 0.11264393478631973 - f1 0.1204080581665039 - sparse_categorical_accuracy 0.2668387293815613
epoch 6 - batch 30 - loss 1.6763923168182373 - precision 0.18646939098834991 - recall 0.1189015656709671 - f1 0.12958459556102753 - sparse_categorical_accuracy 0.2677362263202667
epoch 6 - batch 40 - loss 1.791776418685913 - precision 0.1986534595489502 - recall 0.12240210920572281 - f1 0.1350700706243515 - sparse_categorical_accuracy 0.26685965061187744
epoch 6 - batch 50 - loss 1.6605459451675415 - precision 0.20775678753852844 - recall 0.12581846117973328 - f1 0.13986116647720337 - sparse_categorical_accuracy 0.2670145034790039
epoch 6 - batch 60 - loss 1.665650486946106 - precision 0.21707458794116974 - recall 0.12738101184368134

wandb: Visualizing heatmap.


epoch 6 evaluation time: 16.243706226348877 sec
epoch evaluation:  {'epoch': 6, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.6171263>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.27929145>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.3343803>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.18058692>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.20528105>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 saved checkpoint: models/checkpoints/baseline/ckpt-3
epoch 7 - batch 10 - loss 1.517574667930603 - precision 0.16222058236598969 - recall 0.12692973017692566 - f1 0.1302529126405716 - sparse_categorical_accuracy 0.2805245518684387
epoch 7 - batch 20 - loss 1.7017631530761719 - precision 0.20736698806285858 - recall 0.14779773354530334 - f1 0.1568751037120819 - sparse_categorical_accuracy 0.28182199597358704
epoch 7 - batch 30 - loss 1.609791874885559 - precision 0.23649504780769348 - recall 0.16066405177116394 - f1 0.17374522984027863 - sparse_categorical_accuracy 0.28279390931129456
epoch 7 - batch 40 - loss 1.4575954675674438 - precision 0.2611332833766937 - recall 0.16933153569698334 - f1 0.18576757609844208 - sparse_categorical_accuracy 0.2830357253551483
epoch 7 - batch 50 - loss 1.5307573080062866 - precision 0.2777833938598633 - recall 0.17427882552146912 - f1 0.19346065819263458 - sparse_categorical_accuracy 0.2830524444580078
epoch 7 - batch 60 - loss 1.479000806808471

wandb: Visualizing heatmap.


epoch 7 evaluation time: 15.94413161277771 sec
epoch evaluation:  {'epoch': 7, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.5401634>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.29008618>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.39333633>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.21785963>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.24962534>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 8 - batch 10 - loss 1.4071576595306396 - precision 0.1937474012374878 - recall 0.15382710099220276 - f1 0.15861552953720093 - sparse_categorical_accuracy 0.29500558972358704
epoch 8 - batch 20 - loss 1.4550632238388062 - precision 0.24722541868686676 - recall 0.18158988654613495 - f1 0.19206079840660095 - sparse_categorical_accuracy 0.2948800325393677
epoch 8 - batch 30 - loss 1.3944168090820312 - precision 0.28318291902542114 - recall 0.19761137664318085 - f1 0.21346372365951538 - sparse_categorical_accuracy 0.2955915033817291
epoch 8 - batch 40 - loss 1.3979440927505493 - precision 0.30617713928222656 - recall 0.2069549262523651 - f1 0.22633081674575806 - sparse_categorical_accuracy 0.29541015625
epoch 8 - batch 50 - loss 1.5363491773605347 - precision 0.32855987548828125 - recall 0.2161293476819992 - f1 0.23832978308200836 - sparse_categorical_accuracy 0.2957924008369446
epoch 8 - batch 60 - loss 1.5307122468948364 - precision 0.3422158658504486 - recall 0.22145666182041168 - 

wandb: Visualizing heatmap.


epoch 8 evaluation time: 16.086104154586792 sec
epoch evaluation:  {'epoch': 8, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4837105>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.29848388>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.43298393>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.2525464>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.28708795>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 - batch 10 - loss 1.4325164556503296 - precision 0.2094123363494873 - recall 0.17051592469215393 - f1 0.17485593259334564 - sparse_categorical_accuracy 0.3017578125
epoch 9 - batch 20 - loss 1.3469897508621216 - precision 0.2767554819583893 - recall 0.20927858352661133 - f1 0.22060534358024597 - sparse_categorical_accuracy 0.30602678656578064
epoch 9 - batch 30 - loss 1.3111380338668823 - precision 0.31473496556282043 - recall 0.22874709963798523 - f1 0.24509045481681824 - sparse_categorical_accuracy 0.3067987263202667
epoch 9 - batch 40 - loss 1.4392820596694946 - precision 0.34121644496917725 - recall 0.24135717749595642 - f1 0.26120725274086 - sparse_categorical_accuracy 0.3063197433948517
epoch 9 - batch 50 - loss 1.3063980340957642 - precision 0.36687973141670227 - recall 0.25272998213768005 - f1 0.27643975615501404 - sparse_categorical_accuracy 0.30656808614730835
epoch 9 - batch 60 - loss 1.453955054283142 - precision 0.38310807943344116 - recall 0.25926944613456726 - f1

wandb: Visualizing heatmap.


epoch 9 evaluation time: 16.32961630821228 sec
epoch evaluation:  {'epoch': 9, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4382443>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.30536512>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.46414474>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.27467462>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.3137716>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 9 saved checkpoint: models/checkpoints/baseline/ckpt-4
epoch 10 - batch 10 - loss 1.2900453805923462 - precision 0.22344912588596344 - recall 0.18955622613430023 - f1 0.19109487533569336 - sparse_categorical_accuracy 0.3146205246448517
epoch 10 - batch 20 - loss 1.3742287158966064 - precision 0.2936404347419739 - recall 0.23290303349494934 - f1 0.2418203353881836 - sparse_categorical_accuracy 0.3132393956184387
epoch 10 - batch 30 - loss 1.3724292516708374 - precision 0.33631256222724915 - recall 0.2551572322845459 - f1 0.26926520466804504 - sparse_categorical_accuracy 0.314546138048172
epoch 10 - batch 40 - loss 1.4262694120407104 - precision 0.36497679352760315 - recall 0.26912420988082886 - f1 0.28738677501678467 - sparse_categorical_accuracy 0.3150460422039032
epoch 10 - batch 50 - loss 1.305947184562683 - precision 0.3907868564128876 - recall 0.28031793236732483 - f1 0.30270692706108093 - sparse_categorical_accuracy 0.3155412971973419
epoch 10 - batch 60 - loss 1.32372546195

wandb: Visualizing heatmap.


epoch 10 evaluation time: 15.976161479949951 sec
epoch evaluation:  {'epoch': 10, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.4001706>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31156874>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.48453027>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.3008953>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.33860433>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 11 - batch 10 - loss 1.2637358903884888 - precision 0.23703835904598236 - recall 0.19791436195373535 - f1 0.2026323527097702 - sparse_categorical_accuracy 0.3195870518684387
epoch 11 - batch 20 - loss 1.3106639385223389 - precision 0.30777427554130554 - recall 0.24451030790805817 - f1 0.25401172041893005 - sparse_categorical_accuracy 0.3206891715526581
epoch 11 - batch 30 - loss 1.2164533138275146 - precision 0.3531654179096222 - recall 0.2732234001159668 - f1 0.2880297005176544 - sparse_categorical_accuracy 0.3215401768684387
epoch 11 - batch 40 - loss 1.2596274614334106 - precision 0.38398265838623047 - recall 0.29023095965385437 - f1 0.3087928891181946 - sparse_categorical_accuracy 0.3218122124671936
epoch 11 - batch 50 - loss 1.317415475845337 - precision 0.4125615656375885 - recall 0.3054151237010956 - f1 0.32779282331466675 - sparse_categorical_accuracy 0.32219308614730835
epoch 11 - batch 60 - loss 1.2299480438232422 - precision 0.43132835626602173 - recall 0.3137449622154

wandb: Visualizing heatmap.


epoch 11 evaluation time: 16.004120349884033 sec
epoch evaluation:  {'epoch': 11, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3715593>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3158464>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.49622422>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.32161856>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.357384>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 - batch 10 - loss 1.2712851762771606 - precision 0.24250100553035736 - recall 0.2068951427936554 - f1 0.20973029732704163 - sparse_categorical_accuracy 0.3250837028026581
epoch 12 - batch 20 - loss 1.2936747074127197 - precision 0.3218640983104706 - recall 0.26485252380371094 - f1 0.27204132080078125 - sparse_categorical_accuracy 0.32772043347358704
epoch 12 - batch 30 - loss 1.1666136980056763 - precision 0.37124717235565186 - recall 0.29218748211860657 - f1 0.30543333292007446 - sparse_categorical_accuracy 0.3280971050262451
epoch 12 - batch 40 - loss 1.2287839651107788 - precision 0.40299737453460693 - recall 0.30908262729644775 - f1 0.3273068368434906 - sparse_categorical_accuracy 0.3276785612106323
epoch 12 - batch 50 - loss 1.1892879009246826 - precision 0.43174150586128235 - recall 0.3237380385398865 - f1 0.3462120592594147 - sparse_categorical_accuracy 0.3275502324104309
epoch 12 - batch 60 - loss 1.2689121961593628 - precision 0.4527590274810791 - recall 0.33430859446

wandb: Visualizing heatmap.


epoch 12 evaluation time: 16.29385232925415 sec
epoch evaluation:  {'epoch': 12, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3525788>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.31886306>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.506526>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.33882925>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.3724937>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 12 saved checkpoint: models/checkpoints/baseline/ckpt-5
epoch 13 - batch 10 - loss 1.1820148229599 - precision 0.2515431046485901 - recall 0.21997012197971344 - f1 0.2205493450164795 - sparse_categorical_accuracy 0.3347098231315613
epoch 13 - batch 20 - loss 1.1653343439102173 - precision 0.33216580748558044 - recall 0.27413028478622437 - f1 0.28120851516723633 - sparse_categorical_accuracy 0.3328683078289032
epoch 13 - batch 30 - loss 1.2571516036987305 - precision 0.3829061985015869 - recall 0.30714207887649536 - f1 0.31904277205467224 - sparse_categorical_accuracy 0.33348214626312256
epoch 13 - batch 40 - loss 1.1431890726089478 - precision 0.4154563546180725 - recall 0.3266599476337433 - f1 0.3424660563468933 - sparse_categorical_accuracy 0.3337053656578064
epoch 13 - batch 50 - loss 1.3254690170288086 - precision 0.44065216183662415 - recall 0.33894404768943787 - f1 0.358968049287796 - sparse_categorical_accuracy 0.3326283395290375
epoch 13 - batch 60 - loss 1.16882681846618

wandb: Visualizing heatmap.


epoch 13 evaluation time: 16.26755666732788 sec
epoch evaluation:  {'epoch': 13, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3315607>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3224939>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51673895>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.34422392>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.38069654>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 14 - batch 10 - loss 1.189998984336853 - precision 0.25606468319892883 - recall 0.22498548030853271 - f1 0.22416789829730988 - sparse_categorical_accuracy 0.3368861675262451
epoch 14 - batch 20 - loss 1.178560495376587 - precision 0.33716973662376404 - recall 0.2817124128341675 - f1 0.287433385848999 - sparse_categorical_accuracy 0.33643972873687744
epoch 14 - batch 30 - loss 1.2038265466690063 - precision 0.3911796510219574 - recall 0.3173001706600189 - f1 0.32849231362342834 - sparse_categorical_accuracy 0.33713728189468384
epoch 14 - batch 40 - loss 1.2351361513137817 - precision 0.4299522936344147 - recall 0.34154579043388367 - f1 0.35685333609580994 - sparse_categorical_accuracy 0.3377092778682709
epoch 14 - batch 50 - loss 1.0637308359146118 - precision 0.4608776271343231 - recall 0.35872915387153625 - f1 0.37784743309020996 - sparse_categorical_accuracy 0.3380245566368103
epoch 14 - batch 60 - loss 1.1086084842681885 - precision 0.4772335886955261 - recall 0.36571845412254

wandb: Visualizing heatmap.


epoch 14 evaluation time: 16.08387541770935 sec
epoch evaluation:  {'epoch': 14, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.317663>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3243166>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5169057>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.3580396>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.38993013>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 - batch 10 - loss 1.141377568244934 - precision 0.26882725954055786 - recall 0.2384730726480484 - f1 0.23805482685565948 - sparse_categorical_accuracy 0.3419642746448517
epoch 15 - batch 20 - loss 1.2009563446044922 - precision 0.3504972755908966 - recall 0.29826903343200684 - f1 0.3028557598590851 - sparse_categorical_accuracy 0.34181082248687744
epoch 15 - batch 30 - loss 1.0718615055084229 - precision 0.4059773087501526 - recall 0.33278486132621765 - f1 0.343906432390213 - sparse_categorical_accuracy 0.3430524468421936
epoch 15 - batch 40 - loss 1.0226199626922607 - precision 0.4387100636959076 - recall 0.35195332765579224 - f1 0.36713773012161255 - sparse_categorical_accuracy 0.3437569737434387
epoch 15 - batch 50 - loss 1.0848950147628784 - precision 0.4674282371997833 - recall 0.3703955113887787 - f1 0.3887176215648651 - sparse_categorical_accuracy 0.34268414974212646
epoch 15 - batch 60 - loss 1.1041449308395386 - precision 0.4889632761478424 - recall 0.3819996118545532

wandb: Visualizing heatmap.


epoch 15 evaluation time: 16.01601219177246 sec
epoch evaluation:  {'epoch': 15, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3066106>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.32632768>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51948386>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.36593467>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.39732125>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 15 saved checkpoint: models/checkpoints/baseline/ckpt-6
epoch 16 - batch 10 - loss 1.1238415241241455 - precision 0.26940491795539856 - recall 0.238264262676239 - f1 0.23841582238674164 - sparse_categorical_accuracy 0.34408482909202576
epoch 16 - batch 20 - loss 1.182725191116333 - precision 0.3600638210773468 - recall 0.30441898107528687 - f1 0.3110010623931885 - sparse_categorical_accuracy 0.3455915153026581
epoch 16 - batch 30 - loss 1.1408463716506958 - precision 0.41212496161460876 - recall 0.3396833837032318 - f1 0.3508988916873932 - sparse_categorical_accuracy 0.345610111951828
epoch 16 - batch 40 - loss 1.0589966773986816 - precision 0.45253172516822815 - recall 0.367306113243103 - f1 0.3825702965259552 - sparse_categorical_accuracy 0.34635183215141296
epoch 16 - batch 50 - loss 1.081379771232605 - precision 0.4827421009540558 - recall 0.38505372405052185 - f1 0.4044387638568878 - sparse_categorical_accuracy 0.34617188572883606
epoch 16 - batch 60 - loss 1.137559533119201

wandb: Visualizing heatmap.


epoch 16 evaluation time: 16.045475482940674 sec
epoch evaluation:  {'epoch': 16, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2988875>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.32797462>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5230026>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.37207195>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4032404>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 17 - batch 10 - loss 1.052662968635559 - precision 0.26966527104377747 - recall 0.2425462156534195 - f1 0.2412024587392807 - sparse_categorical_accuracy 0.34815847873687744
epoch 17 - batch 20 - loss 1.1282576322555542 - precision 0.36265531182289124 - recall 0.31077009439468384 - f1 0.31591153144836426 - sparse_categorical_accuracy 0.35050222277641296
epoch 17 - batch 30 - loss 1.1040351390838623 - precision 0.4205840826034546 - recall 0.34904229640960693 - f1 0.3598567545413971 - sparse_categorical_accuracy 0.35113465785980225
epoch 17 - batch 40 - loss 1.1295918226242065 - precision 0.4593820869922638 - recall 0.3773282468318939 - f1 0.39224985241889954 - sparse_categorical_accuracy 0.35080915689468384
epoch 17 - batch 50 - loss 1.1232606172561646 - precision 0.4880032241344452 - recall 0.395905077457428 - f1 0.41341468691825867 - sparse_categorical_accuracy 0.35107702016830444
epoch 17 - batch 60 - loss 1.1839600801467896 - precision 0.5121285915374756 - recall 0.409811973571

wandb: Visualizing heatmap.


epoch 17 evaluation time: 16.12238597869873 sec
epoch evaluation:  {'epoch': 17, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2996784>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.32783693>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52217203>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.37851793>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.40712556>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 - batch 10 - loss 1.0997045040130615 - precision 0.2825041711330414 - recall 0.25268566608428955 - f1 0.25262606143951416 - sparse_categorical_accuracy 0.3510044515132904
epoch 18 - batch 20 - loss 1.094756007194519 - precision 0.3682243824005127 - recall 0.3165842890739441 - f1 0.3218843936920166 - sparse_categorical_accuracy 0.3497767746448517
epoch 18 - batch 30 - loss 1.0276707410812378 - precision 0.4244372546672821 - recall 0.3549901843070984 - f1 0.36549219489097595 - sparse_categorical_accuracy 0.3510974645614624
epoch 18 - batch 40 - loss 1.0712175369262695 - precision 0.4594302177429199 - recall 0.3775090277194977 - f1 0.3916266858577728 - sparse_categorical_accuracy 0.3507254421710968
epoch 18 - batch 50 - loss 1.0152735710144043 - precision 0.49494004249572754 - recall 0.4004281163215637 - f1 0.41849038004875183 - sparse_categorical_accuracy 0.35106584429740906
epoch 18 - batch 60 - loss 1.077418327331543 - precision 0.514086127281189 - recall 0.4140560030937195 - 

wandb: Visualizing heatmap.


epoch 18 evaluation time: 15.987483501434326 sec
epoch evaluation:  {'epoch': 18, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2885274>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3305347>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5267468>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.3831218>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4132016>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 18 saved checkpoint: models/checkpoints/baseline/ckpt-7
epoch 19 - batch 10 - loss 1.057715654373169 - precision 0.28366997838020325 - recall 0.25855007767677307 - f1 0.25707000494003296 - sparse_categorical_accuracy 0.35761719942092896
epoch 19 - batch 20 - loss 1.0333527326583862 - precision 0.37494561076164246 - recall 0.3295380175113678 - f1 0.3320963978767395 - sparse_categorical_accuracy 0.3563058078289032
epoch 19 - batch 30 - loss 1.1179558038711548 - precision 0.42962437868118286 - recall 0.3653116524219513 - f1 0.3731466233730316 - sparse_categorical_accuracy 0.357328861951828
epoch 19 - batch 40 - loss 1.0279256105422974 - precision 0.46992674469947815 - recall 0.39400559663772583 - f1 0.4057638943195343 - sparse_categorical_accuracy 0.3569405674934387
epoch 19 - batch 50 - loss 0.9698960185050964 - precision 0.49872690439224243 - recall 0.41302284598350525 - f1 0.4276680052280426 - sparse_categorical_accuracy 0.3563337028026581
epoch 19 - batch 60 - loss 1.02919375896

wandb: Visualizing heatmap.


epoch 19 evaluation time: 16.059240579605103 sec
epoch evaluation:  {'epoch': 19, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2828779>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3316707>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52731866>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.38918647>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.41724765>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 20 - batch 10 - loss 0.9783420562744141 - precision 0.28779610991477966 - recall 0.25710368156433105 - f1 0.2579778730869293 - sparse_categorical_accuracy 0.35747766494750977
epoch 20 - batch 20 - loss 0.9823098182678223 - precision 0.37390732765197754 - recall 0.3236919045448303 - f1 0.32845547795295715 - sparse_categorical_accuracy 0.35761719942092896
epoch 20 - batch 30 - loss 1.0469975471496582 - precision 0.4291081428527832 - recall 0.3655805289745331 - f1 0.37413108348846436 - sparse_categorical_accuracy 0.35868674516677856
epoch 20 - batch 40 - loss 1.0123847723007202 - precision 0.47178125381469727 - recall 0.39503201842308044 - f1 0.4078119397163391 - sparse_categorical_accuracy 0.3591727018356323
epoch 20 - batch 50 - loss 1.0229878425598145 - precision 0.5030090808868408 - recall 0.41803160309791565 - f1 0.43379437923431396 - sparse_categorical_accuracy 0.35904017090797424
epoch 20 - batch 60 - loss 1.0467760562896729 - precision 0.5296800136566162 - recall 0.434565097

wandb: Visualizing heatmap.


epoch 20 evaluation time: 16.038140058517456 sec
epoch evaluation:  {'epoch': 20, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2790135>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3322541>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5348036>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.387251>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.419243>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 - batch 10 - loss 1.0344698429107666 - precision 0.2931259572505951 - recall 0.2675800919532776 - f1 0.26582470536231995 - sparse_categorical_accuracy 0.36054688692092896
epoch 21 - batch 20 - loss 1.0398585796356201 - precision 0.38583648204803467 - recall 0.33678701519966125 - f1 0.3420928120613098 - sparse_categorical_accuracy 0.3618861734867096
epoch 21 - batch 30 - loss 1.0754643678665161 - precision 0.4394629895687103 - recall 0.3772526979446411 - f1 0.3862002491950989 - sparse_categorical_accuracy 0.36192336678504944
epoch 21 - batch 40 - loss 1.0265636444091797 - precision 0.48305633664131165 - recall 0.4085177779197693 - f1 0.42072755098342896 - sparse_categorical_accuracy 0.3626116216182709
epoch 21 - batch 50 - loss 0.9995347857475281 - precision 0.5139271020889282 - recall 0.4285859763622284 - f1 0.44436362385749817 - sparse_categorical_accuracy 0.36223772168159485
epoch 21 - batch 60 - loss 0.9591578841209412 - precision 0.5415622591972351 - recall 0.4481867253780

wandb: Visualizing heatmap.


epoch 21 evaluation time: 16.136556386947632 sec
epoch evaluation:  {'epoch': 21, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2780665>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33314732>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5311511>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.39873955>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.42510778>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 21 saved checkpoint: models/checkpoints/baseline/ckpt-8
epoch 22 - batch 10 - loss 1.0019785165786743 - precision 0.28983476758003235 - recall 0.2629307508468628 - f1 0.26197561621665955 - sparse_categorical_accuracy 0.3631696403026581
epoch 22 - batch 20 - loss 0.9701491594314575 - precision 0.38801518082618713 - recall 0.34304168820381165 - f1 0.34604936838150024 - sparse_categorical_accuracy 0.3636997640132904
epoch 22 - batch 30 - loss 0.9743903875350952 - precision 0.44592031836509705 - recall 0.38841623067855835 - f1 0.3948102295398712 - sparse_categorical_accuracy 0.3644159138202667
epoch 22 - batch 40 - loss 1.0308257341384888 - precision 0.4881019592285156 - recall 0.41927802562713623 - f1 0.4290296733379364 - sparse_categorical_accuracy 0.36490651965141296
epoch 22 - batch 50 - loss 1.051722764968872 - precision 0.5197730660438538 - recall 0.44047391414642334 - f1 0.45369774103164673 - sparse_categorical_accuracy 0.36490514874458313
epoch 22 - batch 60 - loss 0.92027670

wandb: Visualizing heatmap.


epoch 22 evaluation time: 16.10721516609192 sec
epoch evaluation:  {'epoch': 22, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2771909>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33413658>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.533019>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.394607>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4234509>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 23 - batch 10 - loss 1.0813519954681396 - precision 0.29264035820961 - recall 0.2639908790588379 - f1 0.26401299238204956 - sparse_categorical_accuracy 0.36099329590797424
epoch 23 - batch 20 - loss 0.942427933216095 - precision 0.39134857058525085 - recall 0.34459707140922546 - f1 0.3476179540157318 - sparse_categorical_accuracy 0.3639788031578064
epoch 23 - batch 30 - loss 1.019301176071167 - precision 0.45321401953697205 - recall 0.3932970464229584 - f1 0.3999347686767578 - sparse_categorical_accuracy 0.3666573762893677
epoch 23 - batch 40 - loss 0.9027056097984314 - precision 0.49039867520332336 - recall 0.4219614267349243 - f1 0.4316795766353607 - sparse_categorical_accuracy 0.3670898377895355
epoch 23 - batch 50 - loss 0.9314123392105103 - precision 0.5258837342262268 - recall 0.4461123049259186 - f1 0.4597742259502411 - sparse_categorical_accuracy 0.36670202016830444
epoch 23 - batch 60 - loss 1.0347307920455933 - precision 0.552014172077179 - recall 0.4646713435649872 - f

wandb: Visualizing heatmap.


epoch 23 evaluation time: 16.43713641166687 sec
epoch evaluation:  {'epoch': 23, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.275067>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3344645>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5295917>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.40078282>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.42727333>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 - batch 10 - loss 1.037160038948059 - precision 0.30178704857826233 - recall 0.2743898630142212 - f1 0.27416104078292847 - sparse_categorical_accuracy 0.3678571283817291
epoch 24 - batch 20 - loss 0.9216853976249695 - precision 0.3987390995025635 - recall 0.3571513593196869 - f1 0.3592800498008728 - sparse_categorical_accuracy 0.36905691027641296
epoch 24 - batch 30 - loss 1.0379436016082764 - precision 0.4564964771270752 - recall 0.4000309407711029 - f1 0.4074997305870056 - sparse_categorical_accuracy 0.36917781829833984
epoch 24 - batch 40 - loss 1.0253996849060059 - precision 0.5022583603858948 - recall 0.4328208863735199 - f1 0.44432172179222107 - sparse_categorical_accuracy 0.3700195252895355
epoch 24 - batch 50 - loss 0.9383723139762878 - precision 0.5333250164985657 - recall 0.4551505744457245 - f1 0.46933573484420776 - sparse_categorical_accuracy 0.3702845871448517
epoch 24 - batch 60 - loss 0.9312664866447449 - precision 0.5587295293807983 - recall 0.47539418935775757

wandb: Visualizing heatmap.


epoch 24 evaluation time: 16.76637315750122 sec
epoch evaluation:  {'epoch': 24, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2767807>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3347707>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.53425175>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.40155458>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4289596>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 24 saved checkpoint: models/checkpoints/baseline/ckpt-9
epoch 25 - batch 10 - loss 0.8988428711891174 - precision 0.3091416358947754 - recall 0.2835904359817505 - f1 0.28136351704597473 - sparse_categorical_accuracy 0.37006139755249023
epoch 25 - batch 20 - loss 0.9052664637565613 - precision 0.4013117551803589 - recall 0.36163437366485596 - f1 0.36202913522720337 - sparse_categorical_accuracy 0.37114953994750977
epoch 25 - batch 30 - loss 0.972987949848175 - precision 0.4666927754878998 - recall 0.4107571244239807 - f1 0.41696664690971375 - sparse_categorical_accuracy 0.3726469576358795
epoch 25 - batch 40 - loss 0.9279900193214417 - precision 0.5060877799987793 - recall 0.44126129150390625 - f1 0.4505685567855835 - sparse_categorical_accuracy 0.37333983182907104
epoch 25 - batch 50 - loss 0.9178983569145203 - precision 0.5406805872917175 - recall 0.46632319688796997 - f1 0.47872403264045715 - sparse_categorical_accuracy 0.37283483147621155
epoch 25 - batch 60 - loss 0.995261073

wandb: Visualizing heatmap.


epoch 25 evaluation time: 16.14279580116272 sec
epoch evaluation:  {'epoch': 25, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2777579>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33445364>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5278535>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.40721717>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4306174>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 26 - batch 10 - loss 0.9139879941940308 - precision 0.3049592971801758 - recall 0.2795562148094177 - f1 0.2771114408969879 - sparse_categorical_accuracy 0.37201452255249023
epoch 26 - batch 20 - loss 0.838414192199707 - precision 0.40413394570350647 - recall 0.36445510387420654 - f1 0.365227073431015 - sparse_categorical_accuracy 0.37359094619750977
epoch 26 - batch 30 - loss 0.9258807897567749 - precision 0.46673348546028137 - recall 0.41176533699035645 - f1 0.41685888171195984 - sparse_categorical_accuracy 0.3752976059913635
epoch 26 - batch 40 - loss 0.9097603559494019 - precision 0.5097967982292175 - recall 0.4474160671234131 - f1 0.45480582118034363 - sparse_categorical_accuracy 0.3749930262565613
epoch 26 - batch 50 - loss 0.9789907336235046 - precision 0.5465302467346191 - recall 0.47366973757743835 - f1 0.4847889542579651 - sparse_categorical_accuracy 0.37495535612106323
epoch 26 - batch 60 - loss 0.9181764721870422 - precision 0.5698000192642212 - recall 0.49003851413726

wandb: Visualizing heatmap.


epoch 26 evaluation time: 16.160133600234985 sec
epoch evaluation:  {'epoch': 26, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2815955>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33531785>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52723205>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.40911052>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43173814>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 27 - batch 10 - loss 0.9030645489692688 - precision 0.3094927668571472 - recall 0.28517091274261475 - f1 0.2838389277458191 - sparse_categorical_accuracy 0.3762834966182709
epoch 27 - batch 20 - loss 0.9254060983657837 - precision 0.4117879867553711 - recall 0.3698786199092865 - f1 0.37214189767837524 - sparse_categorical_accuracy 0.37498605251312256
epoch 27 - batch 30 - loss 0.9665213227272034 - precision 0.47009819746017456 - recall 0.4194912612438202 - f1 0.4240545928478241 - sparse_categorical_accuracy 0.37607887387275696
epoch 27 - batch 40 - loss 0.8996275663375854 - precision 0.5135865807533264 - recall 0.4518650472164154 - f1 0.46019163727760315 - sparse_categorical_accuracy 0.3766043484210968
epoch 27 - batch 50 - loss 0.9624435305595398 - precision 0.5490582585334778 - recall 0.4798210561275482 - f1 0.49020156264305115 - sparse_categorical_accuracy 0.37746092677116394
epoch 27 - batch 60 - loss 0.7861552238464355 - precision 0.5755802989006042 - recall 0.49838480353355

wandb: Visualizing heatmap.


epoch 27 evaluation time: 16.195911407470703 sec
epoch evaluation:  {'epoch': 27, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2808776>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3354755>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.524055>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.40836185>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4305088>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 27 saved checkpoint: models/checkpoints/baseline/ckpt-10
epoch 28 - batch 10 - loss 0.9425221681594849 - precision 0.3141264021396637 - recall 0.29318779706954956 - f1 0.2897609770298004 - sparse_categorical_accuracy 0.37215402722358704
epoch 28 - batch 20 - loss 0.9122083783149719 - precision 0.41480523347854614 - recall 0.3798970878124237 - f1 0.3792165517807007 - sparse_categorical_accuracy 0.3752790093421936
epoch 28 - batch 30 - loss 0.9341563582420349 - precision 0.47428691387176514 - recall 0.4233843684196472 - f1 0.4279276728630066 - sparse_categorical_accuracy 0.37677642703056335
epoch 28 - batch 40 - loss 0.8757235407829285 - precision 0.5131862759590149 - recall 0.4570724070072174 - f1 0.4623079001903534 - sparse_categorical_accuracy 0.37759485840797424
epoch 28 - batch 50 - loss 0.9091072678565979 - precision 0.5495460629463196 - recall 0.4834398329257965 - f1 0.49204638600349426 - sparse_categorical_accuracy 0.3777957558631897
epoch 28 - batch 60 - loss 0.84485775232

wandb: Visualizing heatmap.


epoch 28 evaluation time: 15.759036779403687 sec
epoch evaluation:  {'epoch': 28, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.285778>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33606794>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52813655>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41013384>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4333717>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 29 - batch 10 - loss 0.8452790379524231 - precision 0.31764769554138184 - recall 0.2935665547847748 - f1 0.29185014963150024 - sparse_categorical_accuracy 0.3765625059604645
epoch 29 - batch 20 - loss 0.9270256757736206 - precision 0.41877222061157227 - recall 0.38016363978385925 - f1 0.38078707456588745 - sparse_categorical_accuracy 0.3795061409473419
epoch 29 - batch 30 - loss 0.9469054341316223 - precision 0.47559410333633423 - recall 0.4265349507331848 - f1 0.4304716885089874 - sparse_categorical_accuracy 0.37965959310531616
epoch 29 - batch 40 - loss 0.8755725026130676 - precision 0.5205116868019104 - recall 0.4628792107105255 - f1 0.46950551867485046 - sparse_categorical_accuracy 0.380615234375
epoch 29 - batch 50 - loss 0.8343750834465027 - precision 0.5581873655319214 - recall 0.4907078146934509 - f1 0.5006070733070374 - sparse_categorical_accuracy 0.38092634081840515
epoch 29 - batch 60 - loss 0.882610023021698 - precision 0.5838341116905212 - recall 0.5109508633613586 -

wandb: Visualizing heatmap.


epoch 29 evaluation time: 16.040918111801147 sec
epoch evaluation:  {'epoch': 29, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2895832>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3353541>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52760625>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41005343>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43299127>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 30 - batch 10 - loss 0.8409709930419922 - precision 0.3161196708679199 - recall 0.294450044631958 - f1 0.29036933183670044 - sparse_categorical_accuracy 0.3793526887893677
epoch 30 - batch 20 - loss 0.9291436076164246 - precision 0.4159432053565979 - recall 0.379546582698822 - f1 0.3789612352848053 - sparse_categorical_accuracy 0.3805384933948517
epoch 30 - batch 30 - loss 0.9045404195785522 - precision 0.4807746708393097 - recall 0.4273696839809418 - f1 0.4328055679798126 - sparse_categorical_accuracy 0.38131511211395264
epoch 30 - batch 40 - loss 0.9260886907577515 - precision 0.5230675339698792 - recall 0.4638691544532776 - f1 0.47100263833999634 - sparse_categorical_accuracy 0.38178014755249023
epoch 30 - batch 50 - loss 0.9462378621101379 - precision 0.5588129758834839 - recall 0.49305614829063416 - f1 0.5024285912513733 - sparse_categorical_accuracy 0.3808872699737549
epoch 30 - batch 60 - loss 0.7755697965621948 - precision 0.5890757441520691 - recall 0.5176188349723816 - 

wandb: Visualizing heatmap.


epoch 30 evaluation time: 16.005669116973877 sec
epoch evaluation:  {'epoch': 30, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2915018>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33622015>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52824366>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41315255>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4355148>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 30 saved checkpoint: models/checkpoints/baseline/ckpt-11
epoch 31 - batch 10 - loss 0.8829795122146606 - precision 0.31798210740089417 - recall 0.29401490092277527 - f1 0.2920830547809601 - sparse_categorical_accuracy 0.3845982253551483
epoch 31 - batch 20 - loss 0.8718196153640747 - precision 0.4218014180660248 - recall 0.3855191767215729 - f1 0.3857510983943939 - sparse_categorical_accuracy 0.3843750059604645
epoch 31 - batch 30 - loss 0.8706086277961731 - precision 0.4846568703651428 - recall 0.43601855635643005 - f1 0.44061845541000366 - sparse_categorical_accuracy 0.38508185744285583
epoch 31 - batch 40 - loss 0.8588702082633972 - precision 0.5293924808502197 - recall 0.47548818588256836 - f1 0.4811801314353943 - sparse_categorical_accuracy 0.3843889534473419
epoch 31 - batch 50 - loss 0.7919093370437622 - precision 0.566137433052063 - recall 0.5025039911270142 - f1 0.5116892457008362 - sparse_categorical_accuracy 0.3846428692340851
epoch 31 - batch 60 - loss 0.9151535630226

wandb: Visualizing heatmap.


epoch 31 evaluation time: 16.117634773254395 sec
epoch evaluation:  {'epoch': 31, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.2951252>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3357382>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52517>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4125064>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4342135>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 32 - batch 10 - loss 0.8505520820617676 - precision 0.31824779510498047 - recall 0.298446387052536 - f1 0.29507124423980713 - sparse_categorical_accuracy 0.3803292512893677
epoch 32 - batch 20 - loss 0.8253868222236633 - precision 0.4215238392353058 - recall 0.38761699199676514 - f1 0.38705626130104065 - sparse_categorical_accuracy 0.38314732909202576
epoch 32 - batch 30 - loss 0.8924223780632019 - precision 0.48959824442863464 - recall 0.44306620955467224 - f1 0.44622376561164856 - sparse_categorical_accuracy 0.38387277722358704
epoch 32 - batch 40 - loss 0.8705963492393494 - precision 0.5345126986503601 - recall 0.4802573621273041 - f1 0.48586422204971313 - sparse_categorical_accuracy 0.38485631346702576
epoch 32 - batch 50 - loss 0.8650254607200623 - precision 0.5726462602615356 - recall 0.5101466774940491 - f1 0.5185874104499817 - sparse_categorical_accuracy 0.3853515684604645
epoch 32 - batch 60 - loss 0.9183780550956726 - precision 0.595575213432312 - recall 0.5256413817405

wandb: Visualizing heatmap.


epoch 32 evaluation time: 16.17214560508728 sec
epoch evaluation:  {'epoch': 32, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3002821>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3355389>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5212654>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41547057>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.434925>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 33 - batch 10 - loss 0.814703643321991 - precision 0.3205414414405823 - recall 0.3029624819755554 - f1 0.2986775040626526 - sparse_categorical_accuracy 0.38638392090797424
epoch 33 - batch 20 - loss 0.9127470850944519 - precision 0.42832040786743164 - recall 0.3972712755203247 - f1 0.394606351852417 - sparse_categorical_accuracy 0.3873883783817291
epoch 33 - batch 30 - loss 0.8990103602409363 - precision 0.48931044340133667 - recall 0.4482097625732422 - f1 0.4493574798107147 - sparse_categorical_accuracy 0.3880022466182709
epoch 33 - batch 40 - loss 0.8454660773277283 - precision 0.5354304909706116 - recall 0.48582109808921814 - f1 0.4895339012145996 - sparse_categorical_accuracy 0.38719308376312256
epoch 33 - batch 50 - loss 0.8857766389846802 - precision 0.5706871747970581 - recall 0.5123846530914307 - f1 0.5194517374038696 - sparse_categorical_accuracy 0.38708704710006714
epoch 33 - batch 60 - loss 0.8563529849052429 - precision 0.6001999974250793 - recall 0.5381773114204407 -

wandb: Visualizing heatmap.


epoch 33 evaluation time: 16.244258165359497 sec
epoch evaluation:  {'epoch': 33, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3002374>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3355117>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52050203>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41427046>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43326035>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 33 saved checkpoint: models/checkpoints/baseline/ckpt-12
epoch 34 - batch 10 - loss 0.7984441518783569 - precision 0.32046011090278625 - recall 0.30195826292037964 - f1 0.29801860451698303 - sparse_categorical_accuracy 0.3860211968421936
epoch 34 - batch 20 - loss 0.8506132364273071 - precision 0.4291468858718872 - recall 0.39780211448669434 - f1 0.3954537808895111 - sparse_categorical_accuracy 0.3870675265789032
epoch 34 - batch 30 - loss 0.8552631735801697 - precision 0.4923888146877289 - recall 0.45042139291763306 - f1 0.4522498548030853 - sparse_categorical_accuracy 0.38787201046943665
epoch 34 - batch 40 - loss 0.8120654821395874 - precision 0.5391574501991272 - recall 0.49111777544021606 - f1 0.49420982599258423 - sparse_categorical_accuracy 0.38927873969078064
epoch 34 - batch 50 - loss 0.8872595429420471 - precision 0.5760952234268188 - recall 0.5194059610366821 - f1 0.5253989100456238 - sparse_categorical_accuracy 0.3888169527053833
epoch 34 - batch 60 - loss 0.778540611

wandb: Visualizing heatmap.


epoch 34 evaluation time: 15.775673627853394 sec
epoch evaluation:  {'epoch': 34, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3044918>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33560956>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5199782>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41847003>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43577012>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 35 - batch 10 - loss 0.8556758761405945 - precision 0.32023724913597107 - recall 0.30554264783859253 - f1 0.29926368594169617 - sparse_categorical_accuracy 0.3865792453289032
epoch 35 - batch 20 - loss 0.80306476354599 - precision 0.4347879886627197 - recall 0.40488940477371216 - f1 0.40215152502059937 - sparse_categorical_accuracy 0.3890624940395355
epoch 35 - batch 30 - loss 0.872524619102478 - precision 0.4990670382976532 - recall 0.45892778038978577 - f1 0.4596981406211853 - sparse_categorical_accuracy 0.3907366096973419
epoch 35 - batch 40 - loss 0.8966478109359741 - precision 0.5487878918647766 - recall 0.49761807918548584 - f1 0.5021108984947205 - sparse_categorical_accuracy 0.39043664932250977
epoch 35 - batch 50 - loss 0.8343179821968079 - precision 0.5813479423522949 - recall 0.5248595476150513 - f1 0.5311264991760254 - sparse_categorical_accuracy 0.3900613784790039
epoch 35 - batch 60 - loss 0.7681165337562561 - precision 0.6085792183876038 - recall 0.546847939491272 -

wandb: Visualizing heatmap.


epoch 35 evaluation time: 16.144041299819946 sec
epoch evaluation:  {'epoch': 35, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3093711>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33594114>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5252506>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41775873>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4376857>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 36 - batch 10 - loss 0.825172483921051 - precision 0.3300805687904358 - recall 0.3082667589187622 - f1 0.30557096004486084 - sparse_categorical_accuracy 0.38830915093421936
epoch 36 - batch 20 - loss 0.8295662999153137 - precision 0.43037503957748413 - recall 0.40190088748931885 - f1 0.3990859091281891 - sparse_categorical_accuracy 0.39029017090797424
epoch 36 - batch 30 - loss 0.9130455255508423 - precision 0.4957338869571686 - recall 0.45492255687713623 - f1 0.4556248188018799 - sparse_categorical_accuracy 0.39080169796943665
epoch 36 - batch 40 - loss 0.9364131093025208 - precision 0.5436956286430359 - recall 0.4960683584213257 - f1 0.499559611082077 - sparse_categorical_accuracy 0.39130860567092896
epoch 36 - batch 50 - loss 0.8740944862365723 - precision 0.5834611058235168 - recall 0.5273258090019226 - f1 0.5337164402008057 - sparse_categorical_accuracy 0.39099329710006714
epoch 36 - batch 60 - loss 0.7970038056373596 - precision 0.6136299967765808 - recall 0.552500784397125

wandb: Visualizing heatmap.


epoch 36 evaluation time: 16.030407667160034 sec
epoch evaluation:  {'epoch': 36, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3130364>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33549905>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.52109563>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41882455>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43611348>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 36 saved checkpoint: models/checkpoints/baseline/ckpt-13
epoch 37 - batch 10 - loss 0.8057409524917603 - precision 0.3235366642475128 - recall 0.3048504889011383 - f1 0.30087846517562866 - sparse_categorical_accuracy 0.38931360840797424
epoch 37 - batch 20 - loss 0.8297331929206848 - precision 0.4383135735988617 - recall 0.4072832465171814 - f1 0.4054454565048218 - sparse_categorical_accuracy 0.39165735244750977
epoch 37 - batch 30 - loss 0.8094815611839294 - precision 0.49837231636047363 - recall 0.4587177336215973 - f1 0.4587315022945404 - sparse_categorical_accuracy 0.39202940464019775
epoch 37 - batch 40 - loss 0.8105648756027222 - precision 0.5470471382141113 - recall 0.5014061331748962 - f1 0.5039447546005249 - sparse_categorical_accuracy 0.39315709471702576
epoch 37 - batch 50 - loss 0.7423456311225891 - precision 0.5854789614677429 - recall 0.5342481732368469 - f1 0.5383909940719604 - sparse_categorical_accuracy 0.39250558614730835
epoch 37 - batch 60 - loss 0.75205665826

wandb: Visualizing heatmap.


epoch 37 evaluation time: 15.660642385482788 sec
epoch evaluation:  {'epoch': 37, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3145795>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33560956>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51899374>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41697133>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43374252>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 38 - batch 10 - loss 0.8275280594825745 - precision 0.3276195526123047 - recall 0.3122566044330597 - f1 0.30713096261024475 - sparse_categorical_accuracy 0.3913225531578064
epoch 38 - batch 20 - loss 0.8044730424880981 - precision 0.44014066457748413 - recall 0.410001277923584 - f1 0.40724676847457886 - sparse_categorical_accuracy 0.39375001192092896
epoch 38 - batch 30 - loss 0.780009925365448 - precision 0.5011560916900635 - recall 0.4649740159511566 - f1 0.46410098671913147 - sparse_categorical_accuracy 0.39458703994750977
epoch 38 - batch 40 - loss 0.7784355878829956 - precision 0.5566250085830688 - recall 0.5098814368247986 - f1 0.5127094388008118 - sparse_categorical_accuracy 0.3947405219078064
epoch 38 - batch 50 - loss 0.8024630546569824 - precision 0.59056156873703 - recall 0.5370324850082397 - f1 0.5422675013542175 - sparse_categorical_accuracy 0.3940066993236542
epoch 38 - batch 60 - loss 0.7526815533638 - precision 0.6186884045600891 - recall 0.5615891814231873 - f1 0

wandb: Visualizing heatmap.


epoch 38 evaluation time: 16.016427040100098 sec
epoch evaluation:  {'epoch': 38, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3199933>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33548453>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5202221>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41799137>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4355614>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 39 - batch 10 - loss 0.738486111164093 - precision 0.32671675086021423 - recall 0.31160223484039307 - f1 0.3058149516582489 - sparse_categorical_accuracy 0.3913225531578064
epoch 39 - batch 20 - loss 0.8131033182144165 - precision 0.4420223534107208 - recall 0.4122176766395569 - f1 0.40996548533439636 - sparse_categorical_accuracy 0.3936941921710968
epoch 39 - batch 30 - loss 0.8590748906135559 - precision 0.507284939289093 - recall 0.4705428183078766 - f1 0.4692935049533844 - sparse_categorical_accuracy 0.3953869044780731
epoch 39 - batch 40 - loss 0.7739344239234924 - precision 0.5523634552955627 - recall 0.5108993053436279 - f1 0.5114064812660217 - sparse_categorical_accuracy 0.3947056233882904
epoch 39 - batch 50 - loss 0.843040943145752 - precision 0.5901182889938354 - recall 0.5420360565185547 - f1 0.5446884036064148 - sparse_categorical_accuracy 0.39569196105003357
epoch 39 - batch 60 - loss 0.7950435280799866 - precision 0.6192590594291687 - recall 0.568554699420929 - f1 

wandb: Visualizing heatmap.


epoch 39 evaluation time: 16.025537729263306 sec
epoch evaluation:  {'epoch': 39, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3268187>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33556065>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51802886>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41905814>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43633002>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 39 saved checkpoint: models/checkpoints/baseline/ckpt-14
epoch 40 - batch 10 - loss 0.7362160682678223 - precision 0.3264042139053345 - recall 0.31235557794570923 - f1 0.30711305141448975 - sparse_categorical_accuracy 0.3935267925262451
epoch 40 - batch 20 - loss 0.7875548005104065 - precision 0.4462006390094757 - recall 0.4156685471534729 - f1 0.4139213263988495 - sparse_categorical_accuracy 0.39500558376312256
epoch 40 - batch 30 - loss 0.810210645198822 - precision 0.5084472894668579 - recall 0.47176146507263184 - f1 0.4720313549041748 - sparse_categorical_accuracy 0.39587053656578064
epoch 40 - batch 40 - loss 0.820772111415863 - precision 0.5576293468475342 - recall 0.517138659954071 - f1 0.5177639722824097 - sparse_categorical_accuracy 0.3972935378551483
epoch 40 - batch 50 - loss 0.8557814359664917 - precision 0.5942317843437195 - recall 0.5476177334785461 - f1 0.5500353574752808 - sparse_categorical_accuracy 0.39586496353149414
epoch 40 - batch 60 - loss 0.807620704174041

wandb: Visualizing heatmap.


epoch 40 evaluation time: 16.12358283996582 sec
epoch evaluation:  {'epoch': 40, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3284216>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33562407>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51939857>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41721842>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4357029>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 41 - batch 10 - loss 0.8335942625999451 - precision 0.33262598514556885 - recall 0.31670528650283813 - f1 0.3113000690937042 - sparse_categorical_accuracy 0.3960379362106323
epoch 41 - batch 20 - loss 0.7463313937187195 - precision 0.44288545846939087 - recall 0.41274672746658325 - f1 0.41047969460487366 - sparse_categorical_accuracy 0.3956473171710968
epoch 41 - batch 30 - loss 0.8688211441040039 - precision 0.5086173415184021 - recall 0.4717765748500824 - f1 0.4711795449256897 - sparse_categorical_accuracy 0.39675408601760864
epoch 41 - batch 40 - loss 0.7493929862976074 - precision 0.5551947951316833 - recall 0.5122681856155396 - f1 0.5137656927108765 - sparse_categorical_accuracy 0.3965541422367096
epoch 41 - batch 50 - loss 0.8233702778816223 - precision 0.5939459800720215 - recall 0.546699047088623 - f1 0.5493014454841614 - sparse_categorical_accuracy 0.39643415808677673
epoch 41 - batch 60 - loss 0.7649032473564148 - precision 0.6213144659996033 - recall 0.5706716179847717

wandb: Visualizing heatmap.


epoch 41 evaluation time: 16.109997749328613 sec
epoch evaluation:  {'epoch': 41, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3328925>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33554253>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5153626>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.42232862>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4361045>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 42 - batch 10 - loss 0.7522550225257874 - precision 0.33470261096954346 - recall 0.31748998165130615 - f1 0.31303834915161133 - sparse_categorical_accuracy 0.3972935378551483
epoch 42 - batch 20 - loss 0.7584453225135803 - precision 0.4473588764667511 - recall 0.4214009642601013 - f1 0.41776469349861145 - sparse_categorical_accuracy 0.3965959846973419
epoch 42 - batch 30 - loss 0.7726418375968933 - precision 0.5097145438194275 - recall 0.4766938388347626 - f1 0.47513213753700256 - sparse_categorical_accuracy 0.39707961678504944
epoch 42 - batch 40 - loss 0.8047623634338379 - precision 0.5581021308898926 - recall 0.5182923674583435 - f1 0.5185064673423767 - sparse_categorical_accuracy 0.3974330425262451
epoch 42 - batch 50 - loss 0.837124228477478 - precision 0.5940104722976685 - recall 0.5480222702026367 - f1 0.5499687790870667 - sparse_categorical_accuracy 0.39627233147621155
epoch 42 - batch 60 - loss 0.8458914756774902 - precision 0.6198118329048157 - recall 0.5718658566474915

wandb: Visualizing heatmap.


epoch 42 evaluation time: 15.990392446517944 sec
epoch evaluation:  {'epoch': 42, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3364475>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33506602>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5108216>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4211897>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43447006>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 42 saved checkpoint: models/checkpoints/baseline/ckpt-15
epoch 43 - batch 10 - loss 0.7333078384399414 - precision 0.3349539339542389 - recall 0.3226577043533325 - f1 0.3159133791923523 - sparse_categorical_accuracy 0.39545202255249023
epoch 43 - batch 20 - loss 0.8854645490646362 - precision 0.45201292634010315 - recall 0.427227646112442 - f1 0.42240259051322937 - sparse_categorical_accuracy 0.39960938692092896
epoch 43 - batch 30 - loss 0.8410035371780396 - precision 0.5167694091796875 - recall 0.4829613268375397 - f1 0.48044681549072266 - sparse_categorical_accuracy 0.3984375
epoch 43 - batch 40 - loss 0.7774348258972168 - precision 0.5631528496742249 - recall 0.5268294215202332 - f1 0.5249322056770325 - sparse_categorical_accuracy 0.3987862765789032
epoch 43 - batch 50 - loss 0.713960587978363 - precision 0.5988538861274719 - recall 0.5586622953414917 - f1 0.5582184791564941 - sparse_categorical_accuracy 0.39806920289993286
epoch 43 - batch 60 - loss 0.8449443578720093 - prec

wandb: Visualizing heatmap.


epoch 43 evaluation time: 16.093755960464478 sec
epoch evaluation:  {'epoch': 43, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3413886>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33528888>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.50674397>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.42301953>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43419892>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 44 - batch 10 - loss 0.8158575296401978 - precision 0.33718860149383545 - recall 0.3229391872882843 - f1 0.31641238927841187 - sparse_categorical_accuracy 0.39793527126312256
epoch 44 - batch 20 - loss 0.8205648064613342 - precision 0.4532914161682129 - recall 0.4301636219024658 - f1 0.4242498576641083 - sparse_categorical_accuracy 0.39810267090797424
epoch 44 - batch 30 - loss 0.8041073679924011 - precision 0.5169850587844849 - recall 0.4872329533100128 - f1 0.48351195454597473 - sparse_categorical_accuracy 0.3987444341182709
epoch 44 - batch 40 - loss 0.7744048237800598 - precision 0.5636844038963318 - recall 0.5271722078323364 - f1 0.5257040858268738 - sparse_categorical_accuracy 0.3989188075065613
epoch 44 - batch 50 - loss 0.7435593008995056 - precision 0.6007466912269592 - recall 0.557039737701416 - f1 0.5581392645835876 - sparse_categorical_accuracy 0.3993024528026581
epoch 44 - batch 60 - loss 0.7443400621414185 - precision 0.6301547884941101 - recall 0.5826684236526489 -

wandb: Visualizing heatmap.


epoch 44 evaluation time: 16.14884662628174 sec
epoch evaluation:  {'epoch': 44, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3440068>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33456233>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5072071>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4201147>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43274483>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 45 - batch 10 - loss 0.7716659903526306 - precision 0.33614224195480347 - recall 0.32182061672210693 - f1 0.31632962822914124 - sparse_categorical_accuracy 0.3978794515132904
epoch 45 - batch 20 - loss 0.7110881209373474 - precision 0.44839584827423096 - recall 0.42368075251579285 - f1 0.41882041096687317 - sparse_categorical_accuracy 0.4002232253551483
epoch 45 - batch 30 - loss 0.7383629083633423 - precision 0.5167329907417297 - recall 0.48692476749420166 - f1 0.4831453263759613 - sparse_categorical_accuracy 0.40145090222358704
epoch 45 - batch 40 - loss 0.8867273330688477 - precision 0.5645111203193665 - recall 0.5302481055259705 - f1 0.5274947285652161 - sparse_categorical_accuracy 0.40075334906578064
epoch 45 - batch 50 - loss 0.7824739813804626 - precision 0.6028931140899658 - recall 0.5629156827926636 - f1 0.5622293949127197 - sparse_categorical_accuracy 0.40088728070259094
epoch 45 - batch 60 - loss 0.7945658564567566 - precision 0.631140947341919 - recall 0.5859275460243

wandb: Visualizing heatmap.


epoch 45 evaluation time: 16.32962155342102 sec
epoch evaluation:  {'epoch': 45, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3490599>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.3348305>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.5076178>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4216496>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4346005>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 45 saved checkpoint: models/checkpoints/baseline/ckpt-16
epoch 46 - batch 10 - loss 0.7260051369667053 - precision 0.33847305178642273 - recall 0.32483386993408203 - f1 0.31833988428115845 - sparse_categorical_accuracy 0.3970424234867096
epoch 46 - batch 20 - loss 0.7601988911628723 - precision 0.453036904335022 - recall 0.43109628558158875 - f1 0.4247632920742035 - sparse_categorical_accuracy 0.39928850531578064
epoch 46 - batch 30 - loss 0.6760837435722351 - precision 0.5172667503356934 - recall 0.488813579082489 - f1 0.4838714003562927 - sparse_categorical_accuracy 0.4010230600833893
epoch 46 - batch 40 - loss 0.7422930002212524 - precision 0.5679712891578674 - recall 0.5351147651672363 - f1 0.5315499305725098 - sparse_categorical_accuracy 0.40149274468421936
epoch 46 - batch 50 - loss 0.7791756987571716 - precision 0.6058996915817261 - recall 0.5691825151443481 - f1 0.5669692158699036 - sparse_categorical_accuracy 0.4012500047683716
epoch 46 - batch 60 - loss 0.76820313930511

wandb: Visualizing heatmap.


epoch 46 evaluation time: 16.322038650512695 sec
epoch evaluation:  {'epoch': 46, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3547561>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33417282>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.51125824>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.41898453>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43382028>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 47 - batch 10 - loss 0.7317513227462769 - precision 0.3382972776889801 - recall 0.32492828369140625 - f1 0.3186352849006653 - sparse_categorical_accuracy 0.396484375
epoch 47 - batch 20 - loss 0.7931006550788879 - precision 0.4546673893928528 - recall 0.4281580448150635 - f1 0.4241870045661926 - sparse_categorical_accuracy 0.39963728189468384
epoch 47 - batch 30 - loss 0.7624439597129822 - precision 0.5270529985427856 - recall 0.49296391010284424 - f1 0.49086397886276245 - sparse_categorical_accuracy 0.4010602533817291
epoch 47 - batch 40 - loss 0.7739793062210083 - precision 0.5731743574142456 - recall 0.535796046257019 - f1 0.5354551076889038 - sparse_categorical_accuracy 0.40106725692749023
epoch 47 - batch 50 - loss 0.6957069039344788 - precision 0.6075332760810852 - recall 0.5674462914466858 - f1 0.5673028826713562 - sparse_categorical_accuracy 0.4007031321525574
epoch 47 - batch 60 - loss 0.7812575101852417 - precision 0.635419487953186 - recall 0.5912830829620361 - f1 0.59

wandb: Visualizing heatmap.


epoch 47 evaluation time: 16.723098278045654 sec
epoch evaluation:  {'epoch': 47, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.356642>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33438116>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.50946134>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.42386928>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43614405>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 48 - batch 10 - loss 0.760991632938385 - precision 0.33917197585105896 - recall 0.3273111879825592 - f1 0.3208392262458801 - sparse_categorical_accuracy 0.4001116156578064
epoch 48 - batch 20 - loss 0.785504937171936 - precision 0.45581284165382385 - recall 0.435212105512619 - f1 0.4288071393966675 - sparse_categorical_accuracy 0.40205079317092896
epoch 48 - batch 30 - loss 0.7791889905929565 - precision 0.525593101978302 - recall 0.49380332231521606 - f1 0.49156054854393005 - sparse_categorical_accuracy 0.40307849645614624
epoch 48 - batch 40 - loss 0.7559937238693237 - precision 0.5759220123291016 - recall 0.5408950448036194 - f1 0.5387840867042542 - sparse_categorical_accuracy 0.40348073840141296
epoch 48 - batch 50 - loss 0.7656968832015991 - precision 0.6091348528862 - recall 0.5740290284156799 - f1 0.571205198764801 - sparse_categorical_accuracy 0.4033426344394684
epoch 48 - batch 60 - loss 0.7318959832191467 - precision 0.6367107629776001 - recall 0.5981179475784302 - f1 0

wandb: Visualizing heatmap.


epoch 48 evaluation time: 16.441765785217285 sec
epoch evaluation:  {'epoch': 48, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3592545>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33456233>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.50612646>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4246579>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.4352943>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 48 saved checkpoint: models/checkpoints/baseline/ckpt-17
epoch 49 - batch 10 - loss 0.7818347811698914 - precision 0.3357006907463074 - recall 0.3255739212036133 - f1 0.3182152807712555 - sparse_categorical_accuracy 0.4015066921710968
epoch 49 - batch 20 - loss 0.7866564989089966 - precision 0.45922476053237915 - recall 0.4352318346500397 - f1 0.43071919679641724 - sparse_categorical_accuracy 0.4037388265132904
epoch 49 - batch 30 - loss 0.7474452257156372 - precision 0.5221834182739258 - recall 0.49152591824531555 - f1 0.48898619413375854 - sparse_categorical_accuracy 0.40331101417541504
epoch 49 - batch 40 - loss 0.7750116586685181 - precision 0.5743151307106018 - recall 0.5365685224533081 - f1 0.5369170904159546 - sparse_categorical_accuracy 0.40322962403297424
epoch 49 - batch 50 - loss 0.6955814361572266 - precision 0.6114418506622314 - recall 0.5737605690956116 - f1 0.5735780000686646 - sparse_categorical_accuracy 0.4031752347946167
epoch 49 - batch 60 - loss 0.680714488029

wandb: Visualizing heatmap.


epoch 49 evaluation time: 17.822120666503906 sec
epoch evaluation:  {'epoch': 49, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3670012>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33408764>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.49816105>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.4201579>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.429456>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 50 - batch 10 - loss 0.8012212514877319 - precision 0.3431932330131531 - recall 0.3310077488422394 - f1 0.32352373003959656 - sparse_categorical_accuracy 0.40117186307907104
epoch 50 - batch 20 - loss 0.7847316861152649 - precision 0.4573734402656555 - recall 0.4335070252418518 - f1 0.4289427101612091 - sparse_categorical_accuracy 0.40087890625
epoch 50 - batch 30 - loss 0.7659597396850586 - precision 0.5266144275665283 - recall 0.49615195393562317 - f1 0.49330127239227295 - sparse_categorical_accuracy 0.40293899178504944
epoch 50 - batch 40 - loss 0.7125192284584045 - precision 0.5800135135650635 - recall 0.5482656955718994 - f1 0.5452941060066223 - sparse_categorical_accuracy 0.4038783609867096
epoch 50 - batch 50 - loss 0.7806219458580017 - precision 0.6152063608169556 - recall 0.5806769132614136 - f1 0.5786612629890442 - sparse_categorical_accuracy 0.40420758724212646
epoch 50 - batch 60 - loss 0.7839121222496033 - precision 0.6401892304420471 - recall 0.6026710271835327 - f1

wandb: Visualizing heatmap.


epoch 50 evaluation time: 17.45117163658142 sec
epoch evaluation:  {'epoch': 50, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.3682089>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.33437392>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.50616163>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.42379072>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.43450367>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


Saving checkpoint...
Saved checkpoint: models/checkpoints/baseline/ckpt-18
Done saving model
