<a href="https://colab.research.google.com/github/antonpetkoff/identifier-suggestion/blob/master/notebooks/00-colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import utilities
import os
import shutil
from subprocess import check_output

In [2]:
!nvidia-smi

Thu Jun 25 16:12:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [4]:
%env WORKSPACE_DIR=/content/gdrive/My Drive/src

# TODO: how can one read an environment variable?!?
%cd '/content/gdrive/My Drive/src'

env: WORKSPACE_DIR=/content/gdrive/My Drive/src
/content/gdrive/My Drive/src


In [5]:
timestamp = check_output(['date', '-u', "+%Y-%m-%dT%H-%M-%S"]).decode('utf-8').strip()

os.environ['PROJECT_DIR'] = os.path.join(
    os.environ['WORKSPACE_DIR'],
    f'identifier-suggestion-{timestamp}',
)

In [6]:
!git clone https://github.com/antonpetkoff/identifier-suggestion.git --depth 1 "${PROJECT_DIR}"

Cloning into '/content/gdrive/My Drive/src/identifier-suggestion-2020-06-25T16-12-10'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 111 (delta 1), reused 65 (delta 1), pack-reused 0
Receiving objects: 100% (111/111), 1.20 MiB | 1.34 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [7]:
os.chdir(os.environ['PROJECT_DIR'])

In [8]:
!pwd
!ls -l

/content/gdrive/My Drive/src/identifier-suggestion-2020-06-25T16-12-10
total 69
drwx------  4 root root  4096 Jun 25 16:12 data
-rw-------  1 root root 35149 Jun 25 16:12 LICENSE
drwx------  2 root root  4096 Jun 25 16:12 notebooks
-rw-------  1 root root  9745 Jun 25 16:12 README.md
drwx------  3 root root  4096 Jun 25 16:12 reports
drwx------  2 root root  4096 Jun 25 16:12 requirements
drwx------ 13 root root  4096 Jun 25 16:12 src
drwx------  3 root root  4096 Jun 25 16:12 vscode-extension


In [9]:
%tensorflow_version 2.x

import tensorflow
print(tensorflow.__version__)

2.2.0


In [10]:
# Google Colab has standard libraries like numpy, pandas, matplotlib and TF (of course) pre-installed
!pip install -r requirements/colab.txt

In [11]:
# provide secrets to the project, e.g. access to wandb
shutil.copy(
    os.path.join(os.environ['WORKSPACE_DIR'], 'secrets/.env'),
    os.environ['PROJECT_DIR']
)

'/content/gdrive/My Drive/src/identifier-suggestion-2020-06-25T16-12-10/.env'

In [12]:
# monkey-patch (mock) os.symlink to be a noop, because wandb.save() uses it, but it is not supported by Google Colab Notebooks
os.symlink = lambda *x: print('Executing mocked noop symlink with arguments', x)

In [14]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [15]:
from argparse import Namespace
from src.pipelines.baseline import run

params = {
  'dir_data': '../data/processed/subtoken/',
  'file_checkpoint_dir': 'models/checkpoints/baseline/',
  'dir_preprocessed_data': '../data/processed/seq2seq/',
  'max_input_length': 128,
  'max_output_length': 8,
  'input_vocab_size': 5000,
  'input_embedding_dim': 50,
  'output_vocab_size': 5000,
  'output_embedding_dim': 50,
  'latent_dim': 320,
  'learning_rate': 0.0001,
  'epochs': 50,
  'batch_size': 512,
  'random_seed': 1,
  'eval_averaging': 'macro'
}

run(Namespace(**params))

Initializing logger


wandb: Wandb version 0.9.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


Experiment parameters:  Namespace(batch_size=512, dir_data='../data/processed/subtoken/', dir_preprocessed_data='../data/processed/seq2seq/', epochs=50, eval_averaging='macro', file_checkpoint_dir='models/checkpoints/baseline/', input_embedding_dim=50, input_vocab_size=5000, latent_dim=320, learning_rate=0.0001, max_input_length=128, max_output_length=8, output_embedding_dim=50, output_vocab_size=5000, random_seed=1)
Loading preprocessed files...
Loaded input vocabulary.
Loaded output vocabulary.
Loaded preprocessed files.
Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
EncoderEmbedding (Embedding) multiple                  250000    
_________________________________________________________________
EncoderLSTM (LSTM)           multiple                  474880    
Total params: 724,880
Trainable params: 724,880
Non-trainable params: 0
____________________________________________________

wandb: Visualizing heatmap.


epoch 1 evaluation time: 133.86270380020142 sec
epoch evaluation:  {'epoch': 1, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.6290793>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.18866861>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0025760953>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0030731345>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0021288928>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 2 - batch 10 - loss 2.6005313396453857 - precision 0.0024833388160914183 - recall 0.0027896396350115538 - f1 0.001975241582840681 - sparse_categorical_accuracy 0.18858817219734192
epoch 2 - batch 20 - loss 2.5970709323883057 - precision 0.002583203138783574 - recall 0.0028152302838861942 - f1 0.001996571198105812 - sparse_categorical_accuracy 0.18811383843421936
epoch 2 - batch 30 - loss 2.7598767280578613 - precision 0.002885618479922414 - recall 0.002893933327868581 - f1 0.002047799527645111 - sparse_categorical_accuracy 0.18757440149784088
epoch 2 - batch 40 - loss 2.7377572059631348 - precision 0.0028707445599138737 - recall 0.0028426579665392637 - f1 0.0020050336606800556 - sparse_categorical_accuracy 0.18815569579601288
epoch 2 - batch 50 - loss 2.5797173976898193 - precision 0.0031437950674444437 - recall 0.0029489335138350725 - f1 0.002128918655216694 - sparse_categorical_accuracy 0.18816405534744263
epoch 2 - batch 60 - loss 2.5776448249816895 - precision 0.0032698295544

wandb: Visualizing heatmap.


epoch 2 evaluation time: 137.03307819366455 sec
epoch evaluation:  {'epoch': 2, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.3495848>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.20603476>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.022067398>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.013739077>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.011975167>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 - batch 10 - loss 2.3201088905334473 - precision 0.016359280794858932 - recall 0.013336650095880032 - f1 0.011865822598338127 - sparse_categorical_accuracy 0.20454798638820648
epoch 3 - batch 20 - loss 2.3620758056640625 - precision 0.01765352301299572 - recall 0.013457076624035835 - f1 0.011920413933694363 - sparse_categorical_accuracy 0.20527343451976776
epoch 3 - batch 30 - loss 2.457599639892578 - precision 0.019599752500653267 - recall 0.013184807263314724 - f1 0.011914652772247791 - sparse_categorical_accuracy 0.20499442517757416
epoch 3 - batch 40 - loss 2.2880237102508545 - precision 0.021374663338065147 - recall 0.013346939347684383 - f1 0.012302655726671219 - sparse_categorical_accuracy 0.20556640625
epoch 3 - batch 50 - loss 2.4186909198760986 - precision 0.021759286522865295 - recall 0.01356433890759945 - f1 0.012598657049238682 - sparse_categorical_accuracy 0.2052232176065445
epoch 3 - batch 60 - loss 2.3749561309814453 - precision 0.022827358916401863 - recall 0.0

wandb: Visualizing heatmap.


epoch 3 evaluation time: 140.37124848365784 sec
epoch evaluation:  {'epoch': 3, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.081452>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2272836>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.07598984>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.039557163>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.04142519>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 3 saved checkpoint: models/checkpoints/baseline/ckpt-2
epoch 4 - batch 10 - loss 2.1075589656829834 - precision 0.05158768221735954 - recall 0.036735761910676956 - f1 0.036524463444948196 - sparse_categorical_accuracy 0.2289341539144516
epoch 4 - batch 20 - loss 2.2067737579345703 - precision 0.05990521237254143 - recall 0.038434818387031555 - f1 0.03917422518134117 - sparse_categorical_accuracy 0.22841796278953552
epoch 4 - batch 30 - loss 2.025087356567383 - precision 0.06418290734291077 - recall 0.03859277814626694 - f1 0.03967532515525818 - sparse_categorical_accuracy 0.22780877351760864
epoch 4 - batch 40 - loss 2.169969081878662 - precision 0.06779549270868301 - recall 0.03919843211770058 - f1 0.04063590243458748 - sparse_categorical_accuracy 0.2276088148355484
epoch 4 - batch 50 - loss 2.0511343479156494 - precision 0.07076416909694672 - recall 0.03945609927177429 - f1 0.041235364973545074 - sparse_categorical_accuracy 0.22746652364730835
epoch 4 - batch 60 - loss 1.926555

wandb: Visualizing heatmap.


epoch 4 evaluation time: 140.01807188987732 sec
epoch evaluation:  {'epoch': 4, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.8921057>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.24566978>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.15437557>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.07543497>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.08310502>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 5 - batch 10 - loss 1.8723055124282837 - precision 0.0906514897942543 - recall 0.06352628767490387 - f1 0.06612280011177063 - sparse_categorical_accuracy 0.2449776828289032
epoch 5 - batch 20 - loss 1.8030070066452026 - precision 0.10799429565668106 - recall 0.0706324353814125 - f1 0.07504495978355408 - sparse_categorical_accuracy 0.2463727742433548
epoch 5 - batch 30 - loss 1.85234797000885 - precision 0.11856675893068314 - recall 0.07213880866765976 - f1 0.077422134578228 - sparse_categorical_accuracy 0.24573102593421936
epoch 5 - batch 40 - loss 1.8972257375717163 - precision 0.12727123498916626 - recall 0.07387606054544449 - f1 0.08010402321815491 - sparse_categorical_accuracy 0.24656808376312256
epoch 5 - batch 50 - loss 1.7709178924560547 - precision 0.1329701840877533 - recall 0.07518291473388672 - f1 0.08245664834976196 - sparse_categorical_accuracy 0.24657924473285675
epoch 5 - batch 60 - loss 1.8854687213897705 - precision 0.136217400431633 - recall 0.07529208064079285 

wandb: Visualizing heatmap.


epoch 5 evaluation time: 141.89664244651794 sec
epoch evaluation:  {'epoch': 5, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.758591>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.2611136>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.23369753>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.11791673>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.13305175>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 - batch 10 - loss 1.765428900718689 - precision 0.12270670384168625 - recall 0.09107808768749237 - f1 0.0942160114645958 - sparse_categorical_accuracy 0.26428571343421936
epoch 6 - batch 20 - loss 1.8377984762191772 - precision 0.15764528512954712 - recall 0.10446958988904953 - f1 0.1124848872423172 - sparse_categorical_accuracy 0.26340681314468384
epoch 6 - batch 30 - loss 1.7201846837997437 - precision 0.17359194159507751 - recall 0.11115582287311554 - f1 0.12041964381933212 - sparse_categorical_accuracy 0.2643415033817291
epoch 6 - batch 40 - loss 1.854308843612671 - precision 0.18448369204998016 - recall 0.11384040862321854 - f1 0.1250094175338745 - sparse_categorical_accuracy 0.26354631781578064
epoch 6 - batch 50 - loss 1.7034119367599487 - precision 0.19722960889339447 - recall 0.11680501699447632 - f1 0.129930779337883 - sparse_categorical_accuracy 0.263683021068573
epoch 6 - batch 60 - loss 1.7046244144439697 - precision 0.20464091002941132 - recall 0.11688737571239471

wandb: Visualizing heatmap.


epoch 6 evaluation time: 142.88788414001465 sec
epoch evaluation:  {'epoch': 6, 'epoch_test_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.6565787>, 'epoch_test_sparse_categorical_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.27440318>, 'epoch_test_precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.30293065>, 'epoch_test_recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.15967456>, 'epoch_test_f1': <tf.Tensor: shape=(), dtype=float32, numpy=0.18188152>}


wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.
wandb: Visualizing heatmap.


epoch 6 saved checkpoint: models/checkpoints/baseline/ckpt-3
epoch 7 - batch 10 - loss 1.5450986623764038 - precision 0.15190483629703522 - recall 0.11955031752586365 - f1 0.12250936031341553 - sparse_categorical_accuracy 0.27502790093421936
epoch 7 - batch 20 - loss 1.7563154697418213 - precision 0.19824402034282684 - recall 0.1375408172607422 - f1 0.1468460112810135 - sparse_categorical_accuracy 0.2767857015132904
epoch 7 - batch 30 - loss 1.6583950519561768 - precision 0.22345325350761414 - recall 0.14756028354167938 - f1 0.16051127016544342 - sparse_categorical_accuracy 0.2776413559913635
epoch 7 - batch 40 - loss 1.5171457529067993 - precision 0.24320197105407715 - recall 0.1540786623954773 - f1 0.169716477394104 - sparse_categorical_accuracy 0.2781040668487549
epoch 7 - batch 50 - loss 1.592788577079773 - precision 0.2585321366786957 - recall 0.157738596200943 - f1 0.17594601213932037 - sparse_categorical_accuracy 0.277924120426178
epoch 7 - batch 60 - loss 1.527733564376831 - pr

KeyboardInterrupt: ignored